### ISSUE TITLE
Incorrect logic sometimes prevents app from being created

### ISSUE THREAD

**Issue by jessev14** [unsoluble/smalltime#1]
Line 707 of smalltime.js:
```js
} else if (game.settings.get('smalltime', 'visible') === true) {
      const myApp = new SmallTimeApp().render(true);
      game.modules.get('smalltime').myApp = myApp;
}
```

as is, this if-block only runs if the app is already visible. the condition should probably use `!==`

`- enso#0361`

**Comment by unsoluble** [comment]
Hmmm, not sure I follow, but it's probably just my loose understanding of the initialization workflows. The line is meant to prevent the rendering of the window if the value stored in that setting is `false`, because that implies the user has previously toggled the window off.

**Comment by jessev14** [comment]
gotcha, I was trying some stuff out with controlling visibility for players, but this bit works as-is.
