### ISSUE TITLE
Investigate support for other date formats

### ISSUE THREAD

**Issue by Deuterazamus** [unsoluble/smalltime#10]
Simple repro steps:
 - click on the panel to show current date
 - refresh the page
 - panel will be collapsed
Expected behavior: panel should display expanded or collapsed depending on how it was before refreshing.

Also, if possible, please add support for non-US date formats

**Comment by unsoluble** [comment]
Date visibility prefs are now respected on refresh as of 1.6.4. Renamed the ticket to focus on the date display part.

**Comment by unsoluble** [comment]
@Deuterazamus Working on a date-format-choosing UI. What kind of format options would you like to see?

**Comment by unsoluble** [comment]
Implemented chooser in 1.9.0 — let me know if there's a format you'd like that I didn't include.

**Comment by Deuterazamus** [comment]
I've jumped from 1.7.1. to 1.9.5 to get this update but now i get this (no errors in console, btw):

![image](https://user-images.githubusercontent.com/68236513/123558354-0b533200-d796-11eb-88d0-50b74d4f3427.png)

My game is still on 0.7.10, could it be that 0.7.x is not supported?

**Comment by unsoluble** [comment]
Hm. No, 0.7.10 still supported just fine. Try hitting Save in the module settings screen, then do a refresh.

**Comment by Deuterazamus** [comment]
Awesome, that fixed it. Thanks!
Also, available date formats are perfect for me
