### ISSUE TITLE
Addtional 'Player Visibility Default' option

### ISSUE THREAD

**Issue by JustinB555** [unsoluble/smalltime#100]
With the integration with Simple Calendar, I want to be able to use Small Time to be the primary way to show the date, time, and moon. At the moment, it seems that only the GM can see the date, but it would be fantastic if you could add an additional setting to 'Player Visibility Default' for 'Sun/Moon, time, and date'. Love the work, keep it up!

**Comment by unsoluble** [comment]
Hello! The date display is also available to players whenever the time is showing — they just need to click the time to toggle it on. :)

**Comment by JustinB555** [comment]
Ah, guess I completely forgot about that. Just double-checked, yeah, I missed that. Thanks :)
