### ISSUE TITLE
Smalltime Showing on Player's Screen Despite being Disabled

### ISSUE THREAD

**Issue by Nmacpr** [unsoluble/smalltime#101]
Trying to change the player visibility default to 'Sun/Moon' position only, but set to this and also set to 'Nothing' the player still can see the full details of the time and also the date if they double click on the little smalltime window. They cannot change the time however. Repeatable even after multiple refreshes. 

Running on Foundry core 0.8.9, and DnD5e 1.5.5 through Firefox.

Active Modules:
----------
About Time v1.0.4;
Active Token Lighting v0.2.17;
Ambiences Volume 1 - Michael Ghelfi v1.0;
Ambiences Volume 2 - Michael Ghelfi v1.0;
Ambiences Volume 3 - Michael Ghelfi v1.0;
Ambiences Volume 4 - Michael Ghelfi v1.0;
Ambiences Volume 5 - Michael Ghelfi v1.0;
Ambiences Volume 6 - Michael Ghelfi v1.0;
Automatic Journal Icon Numbers vv1.6.0;
Better Rolls for 5e v1.7.0;
Break Time v1.0.11;
Combat Utility Belt v1.7.3;
Confetti v1.0.5;
D&amp;D Beyond Importer v2.7.1;
DF Quality of Life v1.6.1;
DFreds Convenient Effects v1.14.4;
DFreds Droppables v1.3.1;
DF Scene Enhancement v3.4.2;
Dice So Nice! v4.2.2;
Dice Tray v1.2.1;
DnD5e Helpers v3.0.4;
Drag Ruler v1.9.0;
Dynamic Active Effects SRD v6.0.01;
Dynamic effects using Active Effects v0.8.73;
Enhanced Terrain Layer v1.0.34;
FPS Meter v1.1.2;
FXMaster v1.2.1;
GM Notes v0.4.1;
Hey, listen! - Chat Notifications v1.2.3;
Hey, Wait! v0.6.2;
Hide GM Rolls v0.11.0;
Initiative Double Click v1.2;
Less Fog v0.8.6;
lib - Color Settings v2.8.1;
Library: DF Hotkeys v2.3.5;
libWrapper v1.11.0.1;
Loot Sheet NPC 5e v3.2.4;
Lordu's Custom Dice for Dice So Nice v0.33;
Magic Items v2.1.2;
Michael Ghelfi Audio Pack v1.2;
Moulinette Core v3.13.0;
Moulinette Sounds &amp; SoundPad (module) v2.13.0;
Multiple Wall Point Mover (MWPM) v0.5.0;
My Shared Content v1.0.0;
Nap Time (5E) v0.1.1;
Nice More Dice v1.0.3;
Perfect Vision v2.10.1;
Permission Viewer v0.8.14;
Ping Logger v1.2.10;
Pings v1.2.12+0.8.6;
PopOut! v2.4;
Scenery - Background Image Variation Manager v0.1.4;
Settings Extender v1.1.7+9;
Simple Calendar vv1.3.75;
Skill Customization for D&amp;D5e v2.3.0;
SmallTime v1.13.7;
socketlib v1.0.9;
Spell Template Manager v2.1.3;
Stairways (Teleporter) v0.7.5;
Tabletop RPG Music v1.4.0;
Terrain Ruler v1.5.0;
The Rollsmith - Dragon Drogon Dice Set v1.0.0;
The Rollsmith - Dragon Saphira Dice Set v1.0.0;
The Rollsmith - Dragon Smaug Dice Set v1.0.0;
The Rollsmith - Dragon Welsh Green Dice Set v1.0.0;
The Rollsmith - Iridescent Rainbow Dice Set v1.0.0;
Tidy5e Sheet v0.5.20;
Tidy UI - Game Settings v0.1.28;
Timer v0.2.1;
Times Up v0.8.29;
Token Variant Art v1.18.1;
Tome of Beasts by Kobold Press v1.0.3;
Universal Battlemap Importer v2.2.1;

**Comment by unsoluble** [comment]
Are you just setting the _default_ for this in the module settings screen? Making changes there will not affect the current setting in any existing scenes, only new scenes going foward. Check the visibility setting inside the actual scene config, make sure it's set to the level you want.

**Comment by Nmacpr** [comment]
Thanks that fixed it, I thought I'd loaded a new scene since changing the settings, but apparently I didn't. Now working.

**Comment by Nmacpr** [comment]
Actually, playing around with it, I can't see a way to get scenes to just pick the 'default setting' automatically and then be customised further if needed. Is there a way to do that that I'm missing? The scenes are now opening with 'Sun/Moon' only, but would be good if they just immediately switched to 'default' when being created.

**Comment by unsoluble** [comment]
When you create a new scene, its setting is pre-set to whatever you've chosen as the default in Module Settings.

(The `Use default setting` option in scene config isn't actually terribly useful any more and should be removed.)

**Comment by Nmacpr** [comment]
Fair enough then. I quite liked the idea of having the scenes just set to pick up whatever was the default setting from the main settings though, since those kind of things are the things I usually miss until one of my players has to remind me. Would be useful for me anyway since my brain isn't as good as it used to be, that's for sure! But yeah thanks for your help, I appreciate it.

**Comment by unsoluble** [comment]
Yeah unfortunately in order to do that I'd need to hook into every scene load to grab the current default and make sure it's set to that — too much overhead for a niche feature I think.
