### ISSUE TITLE
[BUG] Smalltime vanishes and does not come back.

### ISSUE THREAD

**Issue by Brimcon** [unsoluble/smalltime#103]
When loading into a server and scene for the first time SmallTime can be enabled and disabled normally with a little bit of delay if the left sidebar button is clicked too quickly.
When changing to a different scene and clicking on the SmallTime button to hide the window, clicking the button again will not bring back SmallTime.
The console does say "Rendering SmallTimeApp" when first loading into a scene and when switching scenes, but when you click the button once SmallTime is gone, no console, no error but SmallTime stays gone until refresh.

Foundry Version 9.238
SmallTime Version 1.13.7
Using DnD5e 1.5.6

**Comment by unsoluble** [comment]
Yeah can confirm this. There's something up with the toggle logic that's getting out of sync with the app's render state, I'll investigate when I've got a chance.

In the meantime, just don't spam the toggle button. :)

**Comment by Brimcon** [comment]
Oh of course, just still occurs when I change scenes. I just figured it was related.

**Comment by SLinxTheFox** [comment]
also happens when hitting Escape

**Comment by unsoluble** [comment]
Should be fixed in 1.13.8.
