### ISSUE TITLE
Date not show-/hideable when time is hidden

### ISSUE THREAD

**Issue by veithflo** [unsoluble/smalltime#104]
Hi there. If i press on the time, i can show and hide the current date. But if the time is not displayed for the players, they can't change the display of the date. It's on the last state they had it. And for the worse: the whole layout breaks when displaying the date without time.

Player without Time&Date, everything is fine:
![grafik](https://user-images.githubusercontent.com/32668369/147685747-ff0b538b-2ae0-422a-be88-04fe3ee225b1.png)

Player with Time&Date, everyting is fine:
![grafik](https://user-images.githubusercontent.com/32668369/147685778-f3a941d1-1ab2-47fd-a264-f01404052cab.png)

Player with Date but without Time, it's to big and position is to low. Player have no way to hide Date anymore:
![grafik](https://user-images.githubusercontent.com/32668369/147685850-5866624f-8f0a-4c32-9c24-558eadc8f1a4.png)

**Comment by unsoluble** [comment]
Thanks for catching this — fixed in 1.13.9
