### ISSUE TITLE
Newest update shows a window with the module window controls

### ISSUE THREAD

**Issue by SLinxTheFox** [unsoluble/smalltime#108]
last update was fine, this newest one shows [this here](https://i.imgur.com/aTmy7ZF.png) which closes the small time window if i close it

**Comment by unsoluble** [comment]
Can you elaborate? Foundry and game system versions, still occur with no other modules enabled?

**Comment by SLinxTheFox** [comment]
ugh, my bad, it was somethign with the windows control module, i thought it was small time because it was the only thing i had "open"
