### ISSUE TITLE
Taskbar Support not checking if Move Players is Enabled or not

### ISSUE THREAD

**Issue by mouse0270** [unsoluble/smalltime#109]
Your added support for Taskbar by ripper, always moves the about time widget up 50px even if the taskbar setting to move the players and hotkeys is not enabled, causing a large gap between the players hud element and small time.

Changing the if statement too 
`if (game.modules.get('foundry-taskbar')?.active && game.settings.get('foundry-taskbar', 'moveplayersmacro')) {`

This will fix the issue so the extra padding is only added if taskbar is active and the setting is on.

**Comment by unsoluble** [comment]
Cool, thanks.

**Comment by unsoluble** [comment]
Fixed in 1.13.11
