### ISSUE TITLE
Feature Request - Option to hide from players

### ISSUE THREAD

**Issue by BlitzKraig** [unsoluble/smalltime#11]
It would be nice to have a world option to hide the smalltime display from players.
At the moment, my players are deep inside a mine, and have no way to tell what time of day it is, but it's still handy for me to know.

**Comment by unsoluble** [comment]
Hmm! Fair use case. I'll think about how to do that.

**Comment by unsoluble** [comment]
Added in https://github.com/unsoluble/smalltime/commit/5c14db98c96ee3c560e2cc11e80187f189b1be01
