### ISSUE TITLE
Minor incompatibility with Item Piles

### ISSUE THREAD

**Issue by XtraButtery** [unsoluble/smalltime#114]
[Item Piles](https://github.com/fantasycalendar/FoundryVTT-ItemPiles) has recently updated to add inter-player trading.

The button for trading appears underneath the player indicator though, which causes some problems with SmallTime

When loading in for the first time there is no issue and the SmallTime dock is correctly above the menu.
![image](https://user-images.githubusercontent.com/35461692/153724502-aa376d10-606e-4bbd-8f3d-2d9e83625eba.png)

However after opening or collapsing the players tab SmallTime is no longer correctly positioned.

![image](https://user-images.githubusercontent.com/35461692/153724543-6e92fa5d-1633-47dd-8b43-14c58faf597f.png) ![image](https://user-images.githubusercontent.com/35461692/153724552-0c4182d2-5d44-4722-914a-2749c56f2b81.png)

Dragging the SmallTime window away from the player's section and then snapping it back to the top places it correctly, the issue only arises when it is expanded or collapsed.

![image](https://user-images.githubusercontent.com/35461692/153724610-2afaa6de-a603-4220-88e4-4cb3ded0f1e5.png)

**Comment by unsoluble** [comment]
Thanks, I'll need to add another special consideration for this (there's no way to auto-detect the height of the Players window).

**Comment by unsoluble** [comment]
Fixed in 1.13.14
