### ISSUE TITLE
SmallTime windows covers right click context menu on players indicator.

### ISSUE THREAD

**Issue by XtraButtery** [unsoluble/smalltime#115]
The SmallTime window obstructs the right click context menu when right clicking on a player as a GM.

![image](https://user-images.githubusercontent.com/35461692/153724686-81b614aa-b2cf-4e7d-b2a0-f8f6ce839d6b.png)

This makes it impossible to access certain settings within the menu without first dragging away the SmallTime window.

**Comment by unsoluble** [comment]
This one I can't really solve unfortunately. The Players window would need to be on a higher Z layer than the SmallTime window, but if I put ST below it then it's _also_ below the tool controls layer, which makes elements inside the ST window unclickable. You'll just need to move the ST window in these cases.

**Comment by Ikabodo** [comment]
Understandable!

A few potential workarounds I thought about, just throwing them out there.
1. Hide smalltime window when context menu of the player menu is opened.
2. Hide smalltime window when player menu is hovered over.
3. Use `pointer-events: none´ on the SmallTime window, but I suspect this won't work.
