### ISSUE TITLE
SmallTime windows covers context menu

### ISSUE THREAD

**Issue by Ikabodo** [unsoluble/smalltime#116]
![image](https://user-images.githubusercontent.com/7766890/153749526-b71e3606-ad66-46fa-96fa-3fc8967bb5bb.png)

A small issue, but the SmallTime window seem to cover the context menu of players. It's not often you use that context menu, but it comes up when you for example need to pull a player to a scene. Then you need to move the small time windows first.

**Comment by unsoluble** [comment]
Duplicate of #115 -- sorry, not a trivial fix.
