### ISSUE TITLE
 Window and resolution

### ISSUE THREAD

**Issue by stalker168** [unsoluble/smalltime#117]
It frustrates me a lot when I can't see the module window using other monitors. My main monitor has a resolution of 2K. And when opening the game on other screens with a lower resolution, the window is outside the monitor and cannot be reached.

**Comment by unsoluble** [comment]
You can reset the window's position by Shift-clicking the `Resting Opacity` header in SmallTime's settings screen.

**Comment by stalker168** [comment]
> 
Unfortunately, nothing changes after a reboot.

**Comment by unsoluble** [comment]
Sorry, can you clarify? Nothing changes after Shift-clicking `Resting Opacity`? You may need to elaborate on what exactly is happening.

**Comment by stalker168** [comment]
> 

The SmallTime window does not appear after Shift-clicking the Resting Opacity.

**Comment by unsoluble** [comment]
Can you see the core Players list on the smaller monitor?
