### ISSUE TITLE
Suggestion: Namespace CSS variables

### ISSUE THREAD

**Issue by akrigline** [unsoluble/smalltime#12]
In an effort to avoid module collisions I'd like to recommend you namespace the css variables you define at `:root` level. `--height` and `--opacity` in particular feel prone to accidentally being overwritten by other modules.

**Comment by unsoluble** [comment]
Ahh, fair catch, forgot those'd be in a wider namespace. Thanks!

**Comment by unsoluble** [comment]
Fixed in https://github.com/unsoluble/smalltime/commit/7590f36d092e75e3fc9b26b52f139e7ba404b477
