### ISSUE TITLE
Icon missing

### ISSUE THREAD

**Issue by JonNWN** [unsoluble/smalltime#122]
Sun/Moon icon is missing. I updated and reinstalled but nothing. Any suggestion? 

![image](https://user-images.githubusercontent.com/103656683/163411811-149ef7ae-310e-4c19-9a80-3a43de4ed76a.png)

**Comment by unsoluble** [comment]
How about with no other modules enabled? Probably a CSS conflict at a guess.

Otherwise, check your console (F12 > Console tab) for red errors that might be related.

**Comment by JonNWN** [comment]
I used find the culprit and It was "Dark Matter System Extension" (https://gitlab.com/dark-matter1).

Thanks!
