### ISSUE TITLE
Compatibility with SWADE (system) and Minimal UI (module)

### ISSUE THREAD

**Issue by SalieriC** [unsoluble/smalltime#123]
**SWADE (possibly other systems as well):**
The context menu for players on the SWADE system is rendered behind the Small Time UI, making it impossible to access all options:
![image](https://user-images.githubusercontent.com/1230041/163673066-c5e04b8d-1a48-429b-b16f-716c3b105654.png)
Since the context menu is regularly used in the SWADE system, this makes attaching the Small Time UI there pointless.

**Minimal UI:**
Minimal UI makes the players menu a little smaller and moves it further to the left of the screen, causing the attached Small Time UI to be slightly off-center:
![image](https://user-images.githubusercontent.com/1230041/163673160-02326cf0-2888-49ab-b790-88268f5c4bf9.png)
This one is a very minor problem of course but it is mildly triggering.

Thank you for such a great module however. =)

**Comment by unsoluble** [comment]
Addressed the layer order in 1.13.15. I can't accommodate the Minimal UI module tho, sorry.
