### ISSUE TITLE
Feature: Maximum light/darkness

### ISSUE THREAD

**Issue by JacksonBockus** [unsoluble/smalltime#127]
Let me set a scene's max/min darkness level while still using dynamic darkness. That way for something like a thick forest the light will vary from completely dark to dim instead of from all the way bright to all the way dark.

**Comment by JacksonBockus** [comment]
Well, I had not noticed I could change the heights, and that's great! I do want to clarify that my request would be the ability to override this on a particular scene to make it especially bright or dark.

**Comment by unsoluble** [comment]
Yeaaahhh I'm not gonna do that, as it would require cramming an instance of the config UI into scene config, storing separately, etc.

**Comment by JacksonBockus** [comment]
Fair enough :)
