### ISSUE TITLE
Allow Civil Twilight duration setting

### ISSUE THREAD

**Issue by rpganalyst** [unsoluble/smalltime#128]
Hello, I use Small Time with Simple Calendar running for have seasonal changes in sunrise and sunset times, day by day.
I would like to set the duration of the civil twilight, the time before dawn or after dusk in which is possible to see without artificial lights.
Currently I could mess with the Darkness threshold for toggling Unrestricted Vision Range, but, IMHO, it's not what I would like to see in action.

The option I suggest is kinda this:
Civil Twilight enable/disable
Civil Twilight duration n minutes

E.g. if enabled and its duration set to 30 minutes, then, after sunset, Small Time will begin to raise the darkness value and after 30 minutes it will reach the threshold value for disabling Unrestricted Vision Range.
Viceversa for the dawn.

That way you could have neverending twilights like the ones that happens around the Poles in summer and "normal" ones.

Thank you.

**Comment by unsoluble** [comment]
Hi there! So this sounds like a neat idea, but it's definitely beyond my intended scope for this module. If you're into implementing it and submitting a PR, I'd consider incorporating it.

**Comment by rpganalyst** [comment]
> Hi there! So this sounds like a neat idea, but it's definitely beyond my intended scope for this module. If you're into implementing it and submitting a PR, I'd consider incorporating it.

I'm studying JS, so in the future, this will be definitely a thing I would like to develop. Thank you for your answer.
