### ISSUE TITLE
Feature Request: Optional Lighting Automation From Moon Phases

### ISSUE THREAD

**Issue by DarkSerpent** [unsoluble/smalltime#129]
In games where players travel to the same locations often, it would be neat to have an optional enhancement to automate the phases of the moon causing changes to the Vision Limitation Threshold value on a per-map basis, dependent on Simple Calendar (on maps where "Unrestricted Vision Range" is enabled).

A Full Moon could default with this value at 1.0 (effectively disabled), whereas a New Moon would be somewhere in the ballpark of 0.7, with other phases falling somewhere in-between these values (alongside the potential to change these defaults values in the module settings).

The intention would be to simulate the ample moonlight that would be reflected onto the scene from above, without needing to change the Vision Limitation Threshold on the fly, or set up a complicated network of scripted lights.

**Comment by unsoluble** [comment]
Implemented in 1.14.1
