### ISSUE TITLE
Please add 10 and 15 minutes to Large Step Amount

### ISSUE THREAD

**Issue by apoapostolov** [unsoluble/smalltime#131]
In PF2e I need to use 5 and 10 minutes as periods (5 for moments of talk between the party or simple activities, and 10 for the short rest equivalent in the system). Currently, Large Step starts at 20 minutes.

**Comment by unsoluble** [comment]
Set your Small Step to 5 minutes — you can Shift-click the buttons to double the amount to 10 when needed.

**Comment by apoapostolov** [comment]
Thanks that's very useful thing to remember.
