### ISSUE TITLE
RotF: Is it possible to manually alter the day-night graphic?

### ISSUE THREAD

**Issue by Foundry37** [unsoluble/smalltime#135]
Hello, greatly enjoy the mod. This is less of a request and more of a query for work I can do.

To preface this, I'm running Icewind Dale: Rime of the Frostmaiden soon so I've been preparing.

The setting is currently cursed so that the sun never shines and day doesn't come, instead replaced with a shimmering twilight aurora casting only dim light, the nights are utterly dark and long too as befits an eternal winter, ironically the brightest time is when a full moon comes around.

It's not a serious concern at all as it's a little cosmetic thing, but I was wondering if it was feasible for me to alter the sun graphic and the blue sky graphic to something else by diving into the files or would that break quite a bit?

**Comment by unsoluble** [comment]
Sure, you could tweak those things on your end pretty easily. The sun is represented by two different images — `/images/sun.webp` for the main time slider, and `/images/sun-small.webp` for the darkness level config handles in settings. The sky colour in the time slider background is just a CSS gradient, defined on lines 228-237 in `/styles/smalltime.css`.

Note of course that if you make these changes locally, any future updates to SmallTime will wipe those out, and you'll need to re-apply.
