### ISSUE TITLE
Player List snapping broken when using the mod Breaktime

### ISSUE THREAD

**Issue by apoapostolov** [unsoluble/smalltime#137]
Breaktime (at https://github.com/ironmonk88/breaktime) is a new mod that adds break time management for groups taking a rest, showing who's AFK and who is ready to play. It adds a new line into the Player List, which causes SmallTime to snap badly with the PlayerList and become impossible to manage it's bottom UI.

I reported the issue to IronMonk as well. https://github.com/ironmonk88/breaktime/issues/16

![image](https://user-images.githubusercontent.com/4083812/172233705-f53d2a90-eb3c-4075-b588-9f6cc5a22870.png)

**Comment by unsoluble** [comment]
Yeah I can't possibly accommodate every possible third-party tweak to the surrounding UI; pinning the SmallTime window to the top of Players is already quite complex.

That said, I _am_ working on a feature that'll allow for setting your own custom offset above Players. Just still in the exploration phase.

**Comment by apoapostolov** [comment]
A custom offset would be perfect. It's not hard to set and will fix a lot
of similar problems. Thanks for that.

**Comment by Aeristoka** [comment]
I'll second my desire for this, as I just started using Breaktime this session.

**Comment by unsoluble** [comment]
Sorry for the delay on this — haven't had time to do module dev in quite a while. Hopefully gonna get around to looking at this again in a week or two.

**Comment by unsoluble** [comment]
Added a custom offset in 1.15.4
