### ISSUE TITLE
Window position conflicts with Breaktime Module.

### ISSUE THREAD

**Issue by BlackSwampDM** [unsoluble/smalltime#139]
Love the module, I also use the Breaktime module which adds a Breaktime option to the players bar. This makes the player bar larger. With your window in a fixed position relative to the height of the unmodified player window, it now obscures part of your modules window.
Any luck getting a window position option? Thanks
![Screenshot (2)](https://user-images.githubusercontent.com/98472685/181506564-d90b2687-6314-4a47-8f22-3e04bab5b7fc.png)
.

**Comment by BlackSwampDM** [comment]
I was able to disable breaktime module then move your module then re-enable so, no worries mate. Nevermind. Thanks for a gretat Mod!

**Comment by unsoluble** [comment]
Glad you sorted it out. As noted over in #137, I'm working on a way to nudge the SmallTime window away from Players for cases like this, just isn't done yet.

**Comment by BlackSwampDM** [comment]
Thanks for the response.

**Comment by Aeristoka** [comment]
on 1.15.4, I believe this isn't the intended behavior? 
![image](https://user-images.githubusercontent.com/7988297/194732258-bfcea1bc-1a6e-49b4-8f7d-51a3d5e4ca54.png)

**Comment by unsoluble** [comment]
Mmmm depends? If the SmallTime window was pinned to the top of the Players list, then no it shouldn't do that (but I can't reproduce here). If it was manually placed, it could happen.

**Comment by Aeristoka** [comment]
> Mmmm depends? If the SmallTime window was pinned to the top of the Players list, then no it shouldn't do that (but I can't reproduce here). If it was manually placed, it could happen.

Was snapped to the top of the player list, had all players exit, snapped it to top again, the moment they started loading in (as you can see, I have 7 of them) it got buried again.

**Comment by Aeristoka** [comment]
if I snap it to the top while they're all loaded in, I also get the drag bar buried under the player list:
![image](https://user-images.githubusercontent.com/7988297/194732554-57130ba7-75c5-42e8-9a1f-413a0fa84440.png)

**Comment by unsoluble** [comment]
Yeah I can't reproduce that here no matter what I try. Maybe try a Control-F5, something might be cached?
<img width="245" alt="CleanShot 2022-10-08 at 17 55 25@2x" src="https://user-images.githubusercontent.com/801582/194732623-f9695166-04e5-46ca-857d-3cb22b0b1926.png">

**Comment by Aeristoka** [comment]
I'll fiddle with it more after session... very strange...

**Comment by unsoluble** [comment]
You on Foundry v9 by any chance?

**Comment by Aeristoka** [comment]
> You on Foundry v9 by any chance?

Sure am.

**Comment by unsoluble** [comment]
Got it. Sorry, I haven't been taking the time to test everything thoroughly in v9 on new builds; all my attention's been on v10 lately. Should be working better in 1.15.5 (out in a sec).

**Comment by Aeristoka** [comment]
No worries, appreciate your work! (and your GitHub avatar, showing your disappointment in yourself whenever you commit)
