### ISSUE TITLE
Feature Request - Player-Use

### ISSUE THREAD

**Issue by jasonckramer** [unsoluble/smalltime#14]
Allow a designated player permission and/or actual specific players to manipulate the time. Is that doable? Thanks!

**Comment by unsoluble** [comment]
Thinking about this one. I don't think I'm going to build a thing for choosing specific users, but how about if those with the `Trusted` role could edit? That I might be able to swing.

**Comment by jasonckramer** [comment]
Trusted would be great!

**Comment by unsoluble** [comment]
Implemented as of 1.3.0
