### ISSUE TITLE
Darkness does not drop below 0.6

### ISSUE THREAD

**Issue by Avera9eJoe** [unsoluble/smalltime#140]
When the time is set to midnight, Darkness level doesn't increase more than 0.6, meaning maps never reach their full darkness potential.

Is this intended?

Calendar date is Zarantyr 01, Eberron time

**Comment by unsoluble** [comment]
Either you've got your maximum Darkness level set to that in the module's settings (in the Darkness Configuration tool), or you've got Moon Phase Affects Darkness Level enabled, and the moon is out.

**Comment by Avera9eJoe** [comment]
I don't seem to have any option to change the maximum darkness level inside of the module's settings, but it seems that it *is* being caused by Moon Phase Affects Darkness Levels.

However, my current Simple Calendar Configuration does not have any moons:
![image](https://user-images.githubusercontent.com/5304201/185092051-a225a551-a2cb-4c51-b8f1-384c550fc28f.png)
Is darkness of 0.6 when there are no moons normal?

**Comment by unsoluble** [comment]
Simple Calendar isn't required to have moon phases -- they're displayed on the SmallTime slider, and can be cycled with Shift-click. If you don't want this effect, can disable it in settings.

**Comment by Avera9eJoe** [comment]
I'll disable the light levels dependent on moon phases, that seems the best way to keep light consistently darker. Thank you unsoluble!
