### ISSUE TITLE
[Feature Request] Compatibility with Mass-Edit

### ISSUE THREAD

**Issue by Chryron** [unsoluble/smalltime#142]
Hiya! With the Mass Edit and Multiple Document Selection modules it is possible to change the scene settings for multiple scenes at the same time. Mass-edit is currently adding support for SmallTime to be able to change the settings introduced by smalltime in the scene configuration menu. However, due to the way smalltime displays its settings, it is only possible to force all changes to all of smalltime's settings at once instead of having more granular control. The way to fix this would be to separate the settings using "form-groups".

More details here: https://github.com/Aedif/multi-token-edit/issues/3

**Comment by unsoluble** [comment]
Hmm. I'll take a look when I've got a chance. If this can be done without negatively impacting the current styling it should be an easy tweak.

**Comment by unsoluble** [comment]
Addressed in 1.14.3
