### ISSUE TITLE
[v10] Settings are not displayed correctly

### ISSUE THREAD

**Issue by vt-tom** [unsoluble/smalltime#145]
The new settings are not displayed as they should:
![grafik](https://user-images.githubusercontent.com/80099175/188381337-9fe356b7-484b-4ecd-b243-860b398fe1e7.png)

Foundry 10.284
System DSA/TDE (5t Edition) 4.0.4

**Comment by unsoluble** [comment]
Ugh. Yeah, any system (or module) that changes the core UI is going to mess with my layout in a way that breaks it. Unfortunately a lot of tech debt here in that the original design leaned very heavily on the consistency of the pre-10 window.

I'll see what I can do when I have time, but afraid it won't likely be soon.

**Comment by vt-tom** [comment]
This is only an optical issue, so no need to hurry. 😊
Thanks for the fast reply.

**Comment by Jagusti** [comment]
Popping this screenshot of how WFRP4e handles Smalltime settings. It's not as broken as DSA/TDE, but for reference. As @vt-tom says, it's cosmetic so no rush :) ty 

![image](https://user-images.githubusercontent.com/521096/189363108-487d8cc4-7a24-4634-ad4a-d20fa025678f.png)

**Comment by Txus5012** [comment]
If you widen the window, it will be placed correctly.

**Comment by unsoluble** [comment]
Fixed both in 1.14.6.
