### ISSUE TITLE
v10: Dropping Issues in Console log - limited functionality ?

### ISSUE THREAD

**Issue by gendokun** [unsoluble/smalltime#146]
Smalltime does drop some errors in the console
![grafik](https://user-images.githubusercontent.com/37953318/189231697-1d853724-1f81-449b-b5cd-11b0f817447f.png)

Does that impact the foundry install ?

**Comment by unsoluble** [comment]
Those are all just deprecation warnings; it'll be a while before I'm able to transition the whole thing to v10 methods.

**Comment by gendokun** [comment]
Close
