### ISSUE TITLE
A lot of .data warnings on v10

### ISSUE THREAD

**Issue by mkahvi** [unsoluble/smalltime#147]
Although the module seems functional in v10, there's a lot of compatibility warnings.

If these are kept intentionally to rely on the shims, the module should add itself to the exclusions.

Ref: <https://github.com/foundryvtt/foundryvtt/issues/6890>

**Comment by unsoluble** [comment]
This is only "intentional" as in "haven't had time to address the changes." Will consider the exclusions route tho.
