### ISSUE TITLE
Tool doesnt work in the System "Das Schwarze Auge/The Dark Eye (5th Edition)"

### ISSUE THREAD

**Issue by tomsaath** [unsoluble/smalltime#15]
I installed the module with AboutTime and Calendar/Weather, but the control panel doesnt work. 

Here ist what it looks like in the System "Das Schwarze Auge/The Dark Eye (5th Edition)"
![grafik](https://user-images.githubusercontent.com/80099175/117565809-8d3aaf00-b0b3-11eb-998a-520ab20c2828.png)

I would like if you can make it compatible.

Here ist the github link from the System:
https://github.com/Plushtoast/dsa5-foundryVTT

**Comment by unsoluble** [comment]
Hmm! Looks like that system is overriding a bunch of styles. Not sure how easy this'll be to work around, but I'll investigate. Thanks for the heads-up. :)

**Comment by tomsaath** [comment]
I like to hear that, thank you for trying.

**Comment by tomsaath** [comment]
This looks awesome. Thank you very much!
