### ISSUE TITLE
Feature suggestion: Custom moon images

### ISSUE THREAD

**Issue by Danii0206** [unsoluble/smalltime#154]
Hi,

thank you very much for this module! Since we use this, my players don't ask "what time is it?" as much as before. ^^ 

My system uses a moon that's laying on the side. I have images to represent this. But as is I have to copy them into the module folder everytime the module is updated - which I often forget, to be honest. So in foundry our moon sometimes is correct, sometimes it's 90° off until I see it mid-game.

Is it possible to have an option to provide a path to a folder outside the module with custom moon images, so it doesn't reset those images on every update?

Kind regards
Danii

**Comment by unsoluble** [comment]
Hello! Glad you're enjoying the module. :)

While I can't really accommodate a custom image path, I can offer _perhaps_ a workaround? I don't really grok the physics of how your moon works, but if the aesthetic end goal you're aiming for is to have all the same phases but rotated 90°, you can achieve that with CSS:
<img width="607" alt="CleanShot 2022-10-08 at 13 19 18@2x" src="https://user-images.githubusercontent.com/801582/194726550-61afcb09-3fce-4287-809a-5349c4448d0a.png">
(using the Custom CSS module here to make the changes persist, and the two similar rules to cover both Chromium and Firefox browsers)
