### ISSUE TITLE
Console error when loading scene

### ISSUE THREAD

**Issue by MorganVergara** [unsoluble/smalltime#155]
Good day,

I noticed this console error popping up when loading a scene.

![image](https://user-images.githubusercontent.com/30846057/194762653-24985d3f-bc92-4b6c-bcf0-5fd5ce06d008.png)

It doesn't seem to actually affect the display. The position of SmallTime is maintained correctly on the scene, even during reloads of the browser. It's recent; only started happening yesterday (Saturday, 8 Oct). The day before it was fine while I was doing game prep.

This is mostly to bring it to your attention in case it's a symptom of a larger bug that may be causing problems for someone else.

Thanks!

Morgan

**Comment by unsoluble** [comment]
Thanks for the report! What version of SmallTime? This was an issue in 1.15.4, should be fixed in 1.15.5 (released shortly after).

**Comment by MorganVergara** [comment]
It is 1.15.4. I'll try upgrading and see if that fixes it.

**Comment by MorganVergara** [comment]
I no longer see the error with 1.15.5! That's the good news. The bad news (and I'm not sure it's an issue with SmallTime) is that when snapping to the player menu, it snaps properly, but if one's game has a larger number of icons in the command menu on the left, the ones that are at the bottom (just above the player menu) are rendered on top of SmallTime.

![image](https://user-images.githubusercontent.com/30846057/194774479-f208a91e-36c5-4967-8e0e-c7a4045d832f.png)

If I expand the player menu, the icons are properly rendered with regard to the player menu, but the rendering continues to ignore SmallTime.

![image](https://user-images.githubusercontent.com/30846057/194774516-5b561dca-ab5c-4d54-b05f-bb7507234ad6.png)

As I said, I'm not sure if that's your issue to fix or a glitch with core Foundry, but I thought I'd let you know. Incidentally, the previous version did not properly "stick" to the player menu when docked on top of it. Was that the fix that was implemented in 1.15.5?

Thanks!

Morgan

**Comment by unsoluble** [comment]
Yeah I can't do anything about collisions between SmallTime and the toolbar; the solutions are to move it elsewhere, use fewer modules that add tools, find a module that changes the layout there, or get a larger screen. :)

**Comment by MorganVergara** [comment]
I figured that was the case :)  No worries. Thanks for the quick replies and for all the work. SmallTime is a pleasure to use. I think we can close this issue.
