### ISSUE TITLE
Not moveable because obstructed

### ISSUE THREAD

**Issue by donmanolito** [unsoluble/smalltime#156]
The clock window is not moveable because after the latest update it sits right below the players window and i can't hover the section where you should be able to move it. 

Could you put in a reset position button in the configure window or any other possibility to move it again?!

**Comment by donmanolito** [comment]
Yes its 1.15.5 

Shit clicking on the Resting Pacity header doesn't change anything.

**Comment by unsoluble** [comment]
Sorry, I can't reproduce this behaviour, so not sure what to suggest. Perhaps try with no other modules enabled, see if you can get the reset to work. It should re-pin the SmallTime window to the top of the Players list.
