### ISSUE TITLE
[Bug] Midnight is outside of container

### ISSUE THREAD

**Issue by mouse0270** [unsoluble/smalltime#158]
To get set sunset to midnight you have to drag the moon outside of the container. However, sunrise midnight is still in the container.

Not sure if this is an actual bug or just an odd visual issue
![image](https://user-images.githubusercontent.com/564874/195998304-7b7ec17b-f258-4291-8c1e-ebf3174799bb.png)

**Comment by unsoluble** [comment]
Yeah this is currently expected, as I had to shrink the size of the container to fit within the new Settings layout, and making all the child elements adjust accordingly wasn't worth the effort (yet). I'll keep this open as a reminder that I'll need to address this eventually tho.

**Comment by unsoluble** [comment]
Fixed in 1.16.6
