### ISSUE TITLE
[Feature Request] Lighting for multiple moons

### ISSUE THREAD

**Issue by Berytak** [unsoluble/smalltime#159]
Hey there,

first of all, I really love this module. It's just perfect that the lighting is adjusted to suit the time of day. Now that the scene can also be illuminated by the moon phase from the Simple Calendar, I wanted to ask if it would also be possible to support multiple moons?
As far as I know, the illumination is only set on the basis of the first moon.
Simple Calendar offers the possibility to configure several moons and their colour, so it would be great if the second moon could also be taken into account. I would also be happy if the configured colour of the moons in Simple Calendar had an effect on the illumination.
As a side note, I am currently running a Warhammer campaign and there are two moons in the world, one of which (Morrslieb) is green.

Cheers
Berytak

**Comment by unsoluble** [comment]
Hiya! Thanks for the kind words, and for the descriptive request. Could you elaborate a bit on how you envision this working?

- Aside from colour stuff, what would the multiple moons functionally _do_ in the SmallTime interface?
- How should they be represented?
- Would the colour of a moon actually impact the Darkness colour of scenes? Feels to me like moon colour on its own wouldn't affect that at all?

**Comment by Berytak** [comment]
Hi @unsoluble 
Of course, I'm happy to elaborate a little further.

If I have understood the option "Moon Phase Effects Darkness" correctly, the moon phase simply sets the maximum darkness at night within a scene. But this is only influenced by the first moon configured in Simple Calendar. The second moon has no effect on this option.

![image](https://user-images.githubusercontent.com/85394657/197458448-bbfda1fd-bab8-4061-bbd8-f61173c89896.png)

In this case only "Mannslieb" affects the darkness setting but not "Morrslieb".
You can also set the colour of the moons in the Simple Calendar options. I don't know if it's possible to change the colour of the global illumination, but I suppose that would be a suitable option.
"Morrslieb" creates an eerie green glow and seeing that in a scene would be awesome without having to adjust the lights every time.

Example of what it could look like.
![image](https://user-images.githubusercontent.com/85394657/197458627-64668de1-f763-4ddd-b1ba-7054611ba956.png)

So let's summarise again:

- Moons created in Simple Calendar after the first one should also affect the darkness settings.
- It would be great if the scene gets a colour tint of the configured moon colour at night. (A full moon would probably be enough).

But I'm actually not sure if this can be realised and if so, then how.

I apologise if I have not made myself clear, but English is not my first language.

Cheers
Berytak

**Comment by Peach774** [comment]
I want to add to this - it would be nice to be able to configure how bright each moon IS. I have 2 moons and when both are full its nearly as bright as daylight, when one of the moons shouldn't give much light, and if the above was implemented, would really only provide a tint to said light.
So an option to configure how 'bright' each moon is when the setting is enabled would be great, since right now, I have to disable this feature otherwise many nights are too bright.

**Comment by unsoluble** [comment]
Can tell you both straight-up that I'm not going to be implementing support for more than one moon — that'd be an exponential nightmare of complexity. Changing the Darkness tint based on a colour pulled from SC is theoretically possible, will look into it. Adding a config for the percentage impact that the phase brightness has on scene Darkness is also feasible. Extremely limited free time these days tho, so might be a while.

**Comment by unsoluble** [comment]
Moon tint and phase impact have been added in 1.19.0
