### ISSUE TITLE
Integration with PF2E world clock

### ISSUE THREAD

**Issue by ElroTheOnk** [unsoluble/smalltime#16]
Hi. I really like the aesthetic of this module for "player awareness". I wonder if there's any prospect of syncing to the PF2E World Clock in the same way that it looks like you do with AboutTime? (The latest version of PF2E does not play nicely with AboutTime.)

**Comment by unsoluble** [comment]
Ughhh why does PF2E have to do _everything_ on its own. I think probably the answer is no, trying to incorporate two separate sync sources is beyond what I'm interested in doing, but I'll take a look. Would be great if the PF2E folks could figure out how to send to AT though.

**Comment by unsoluble** [comment]
Hey @ElroTheOnk, I've done a bunch of testing here with a fresh PF2E world and just About Time and SmallTime enabled, and everything syncs up just fine via the PF world clock tool. Can you perhaps try testing without other modules enabled?

**Comment by ElroTheOnk** [comment]
Thanks for looking into it - yes, with About Time enabled all would be fine *for time syncing*. That isn't a solution for me at the moment though; I should probably have been more verbose in the original issue, apologies.

PF2E has recently enabled automation of effect expiry which does not work properly with About Time enabled according to my Find the Culprit investigation (though you are correct: the world clock syncing bit works just fine). Since PF2E uses effects very freely, I've had to disable About Time (which I previously merrily used) as I need effect expiry working properly more than I need an in-game time tracker. I am now using Small Time as my "player clock display" (in lieu of Calendar/Weather, which I was using previously, but which is hard-dependent on About Time), and advancing it manually as I move the PF2E World Clock on. I hoped it might be straightforward to offer a sync option from Small Time directly to the PF2E World Clock instead of About Time, but I understand that this may not be a thing you wish to support!

I will ask at the PF2E end for a fix wrt About Time (& I think one of the PF2E devs has also asked re a fix at the About Time end).

**Comment by tposney** [comment]
Not a smalltime issue, but I just tested the about-time/pf2e interaction issue and could not repro with pf2e 1.15

**Comment by ElroTheOnk** [comment]
Resolved - root cause was an non-rules default user setting in the world in question causing PF2E & About TIme to interact peculiarly.
