### ISSUE TITLE
Automated darkness on scenes is not working 

### ISSUE THREAD

**Issue by ctbritt** [unsoluble/smalltime#160]
the automated darkness has gone wonky with the latest update, I think. 

I have my seasons set in Simple Calendar. All seems to be working there. But when I have a scene with Global Illumination enabled like so: 
<img width="482" alt="CleanShot 2022-10-27 at 22 34 11@2x" src="https://user-images.githubusercontent.com/4516034/198382087-762f4440-3027-41c9-b267-0cf32676d949.png">

and darkness control and moonlight adjustment enabled, the darkness of the scene starts alternating with every tick of the clock. 

I have the settings in small time set to this: 
<img width="547" alt="CleanShot 2022-10-27 at 22 35 47@2x" src="https://user-images.githubusercontent.com/4516034/198382413-51eb07ea-2f10-41a6-b143-a2894ff361e1.png">

As you can see, it's NOT getting the season's sunrise and sunset from Simple Calendar (which is set to 0500 - 2030 for sunrise and sunset). It's smooshing the sunrise and sunset over to the left. 

And this is what it looks like when the game is unpaused and the time is allowed to run: 

https://user-images.githubusercontent.com/4516034/198383056-4e2a3762-2a67-4b12-949e-16e810138465.mp4

I'm not getting any errors or warnings in the console. So, not sure what is going on....

**Comment by unsoluble** [comment]
How about with nothing but SmallTime and Simple Calendar enabled? All that GI config stuff is third-party.

**Comment by ctbritt** [comment]
yes, with just SC and ST, i get the same effect.

**Comment by ctbritt** [comment]
Ok. I've removed seasons from the calendar, removed any moons, and even created a new test calendar based on the gregorian (sans moon and seasons). Still getting the flashing every tick of the game clock.

**Comment by ctbritt** [comment]
this is with just SC and ST enabled. Nothingf else.

**Comment by unsoluble** [comment]
Try a new world perhaps? I haven't seen anything like this.

**Comment by ctbritt** [comment]
OK. Now the handles are stuck outside the window where I can drag them. 

<img width="624" alt="CleanShot 2022-10-27 at 22 56 41@2x" src="https://user-images.githubusercontent.com/4516034/198386047-25d24e03-77c3-44b6-98d5-e4b42f21993e.png">

**Comment by ctbritt** [comment]
the moons and sons can be dragged vertically, but not horizontally.

**Comment by ctbritt** [comment]
ok. tried it with a new test world. It works ok. So I guess there's something wonky in the settings? how would I reset them back to zero?

**Comment by unsoluble** [comment]
Does it work as expected in the first world if you have the sunrise/set sync disabled?

**Comment by ctbritt** [comment]
yes, it seems to work just fine in the test world.

**Comment by ctbritt** [comment]
here are the ST settings from an export of my main foundry settings: 
```
{
    "key": "smalltime.current-date",
    "value": "\"Flamerule 18th, 1492  DR\""
  },
  {
    "key": "smalltime.date-showing",
    "value": "true"
  },
  {
    "key": "smalltime.moon-darkness",
    "value": "true"
  },
  {
    "key": "smalltime.moon-phase",
    "value": "1"
  },
  {
    "key": "smalltime.pinned",
    "value": "false"
  },
  {
    "key": "smalltime.player-visibility-default",
    "value": "\"2\""
  },
  {
    "key": "smalltime.position",
    "value": "{\"top\":680,\"left\":535}"
  },
  {
    "key": "smalltime.small-step",
    "value": "5"
  },
  {
    "key": "smalltime.sun-sync",
    "value": "true"
  },
  {
    "key": "smalltime.sunrise-end",
    "value": "0"
  },
  {
    "key": "smalltime.sunrise-start",
    "value": "-120"
  },
  {
    "key": "smalltime.sunset-end",
    "value": "120"
  },
  {
    "key": "smalltime.sunset-start",
    "value": "0"
  },
```

**Comment by unsoluble** [comment]
If it works as expected with the SC sync disabled, then it's most likely that there's something weird going on with your rise/set times as set in SC (or your other date/time stuff over there is nonstandard in some way I don't support).

**Comment by ctbritt** [comment]
In the original world (with the issue) it has the same problem whether SC sync is turned on or not.

**Comment by unsoluble** [comment]
Is it the same with SC disabled?
