### ISSUE TITLE
SmallTime V1.15.8 breaks visibility for GM in DnD5e

### ISSUE THREAD

**Issue by buttonpushertv** [unsoluble/smalltime#162]
On V10.288 & DnD5e v2.0.3, with only SmallTime v.1.15.8 and About Time 10.0.1 installed in a fresh World, the SmallTime window is never visible for the GM, but Players can see it. Toggling it on and off via the tool bar icon makes the notification in the console appear but never makes it visible for the GM. It does appear to work correctly for Players.

Rolling back to SmallTime v1.15.7 restores GM visibility.

**Comment by unsoluble** [comment]
I can't replicate this. Are you sure it's not visible anywhere in the viewport? No errors in the console on toggling?

**Comment by buttonpushertv** [comment]
So it must've been way off screen for me. I downgraded to 1.15.7. Then I could see it where I thought it should be and I moved it back to right on top of the Player listing. I then updated back to 1.15.8 and its back on-screen.

FWIW, there was no error in console, just the message it usually displays when you show or hide it.
