### ISSUE TITLE
[Feature Request] - Integration with weather control

### ISSUE THREAD

**Issue by mafamac** [unsoluble/smalltime#168]
![Untitled](https://user-images.githubusercontent.com/6748594/211193314-224037ab-bb44-4ca5-ad30-94e00ea1ccfd.png)
Hello,

Is it possible add support to the weather control module?
https://gitlab.com/jstebenne/foundryvtt-weather-control

this way we can have only one calendar and choose what players can see.

I'll post this feature request to weather control as well because i'm not sure if at this point this is possible.

Now we have 2 maps on the scene (also weather control doen't allow us to hide time from players and maybe smalltime can allow us to show/hide the weather from the smalltime bar).

Below the GM's vision

![example](https://user-images.githubusercontent.com/6748594/211192899-9d80e61f-be4e-46d7-8d07-5812f69e14fa.png)

Below the player's vision
![exaMPLE2](https://user-images.githubusercontent.com/6748594/211193138-5611e9cd-6b89-4541-980c-ee60a165e6fe.png)

my idea is have something like the small time calendar shows with the weather on the right
![Untitled](https://user-images.githubusercontent.com/6748594/211193322-2e82568e-07f4-4666-b8b0-e12064a31a82.png)

**Comment by unsoluble** [comment]
Hi there! Thanks for the write-up, but I'm fairly sure this isn't going to be something I'm going to implement. You might want to look into the [SmallWeather](https://foundryvtt.com/packages/smallweather) module as an alternative?
