### ISSUE TITLE
Feature Request - Movable UI

### ISSUE THREAD

**Issue by themadphoenix** [unsoluble/smalltime#170]
With the UI in the lower left hand corner and unmovable, it interferes with minimal UI which moves the Macro Bar and User list into the lower left hand corner.  It would be better if it weren't locked into that corner and was movable to where it worked best for each individual user.

**Comment by unsoluble** [comment]
Hi there! It's always movable — the bar at the bottom of the window is a drag handle.

**Comment by themadphoenix** [comment]
Hi, yeah, I just found that.  Since I'm usually looking for the drag handle at the top or side and that's at the very bottom of the screen that was not immediately obvious.
