### ISSUE TITLE
Seconds not showing in SmallTime

### ISSUE THREAD

**Issue by MorganVergara** [unsoluble/smalltime#172]
Note that the display is not wide enough to show seconds:

![image](https://user-images.githubusercontent.com/30846057/224460585-a379c067-6352-44b9-b6c8-2c2cca798bd5.png)

If you turn off seconds display, the final ":" disappears. Changing to 12 hour time display removes the option to display seconds at all. (Not sure if that's intentional or another bug.)  Changing time display also requires a restart to take effect. 

Clicking the time to turn on and off the date does this:

![image](https://user-images.githubusercontent.com/30846057/224460882-3c4df681-f104-47ac-8386-432261aa19f4.png)

Tried FindTheCulprit with only SmallTime, SimpleCalendar, libWrapper, and socketLib, still has the same problem. Is there a way to make it wider?

Foundry v10.291, D&D 5e 2.1.5, and SmallTime 1.16.3. 

Thanks!

**Comment by unsoluble** [comment]
Can't reproduce under normal conditions. Is your core Font Size set above 5, by any chance?

It's intentional that there are no seconds in the 12hr display, as there isn't room for both seconds and am/pm.

**Comment by MorganVergara** [comment]
Hah! That was it! I didn't even realize it had gotten set to 6. Must have
been a slip of the mouse some time ago!

And I figured that was probably the case on the 12 hour display.

Thanks for the help and glad it was an easy fix!

Morgan
