### ISSUE TITLE
Deprecation warning regarding Scene#data object which is no longer used.

### ISSUE THREAD

**Issue by thatlonelybugbear** [unsoluble/smalltime#174]
Foundry 10.291
Dnd5e 2.2.1
SmallTime 1.16.5

Every second a deprecation warning is logged, regarding [https://github.com/unsoluble/smalltime/blob/cb068d96639617ad38b97c70ec2f0f8fca736b99/scripts/helpers.mjs#L744](url), 
reading the `data` in
```js
if (newThreshold === game.scenes.viewed.data.globalLightThreshold) {
      return true;
}
```

**Comment by unsoluble** [comment]
Fixed in 1.16.6
