### ISSUE TITLE
BUG: Darkness Configuration doesn't let me make it brighter than 0.1. 

### ISSUE THREAD

**Issue by GambetTV** [unsoluble/smalltime#175]
When going into the settings and dragging the Suns up as high as they'll go, it seems to only get me to 0.1 Darkness Level. Which means none of my maps can ever get to maximum brightness. I could be wrong, but I don't remember this being an issue in 1.6.2.

**Comment by unsoluble** [comment]
Hmm, will check it out. Had to revamp a bit of the CSS in the Settings window, so the grid snapping for the drag handles might've gotten off by a bit. Thanks!

**Comment by unsoluble** [comment]
Fixed in 1.16.6
