### ISSUE TITLE
Player see only sun and moon positons not working

### ISSUE THREAD

**Issue by Alecell** [unsoluble/smalltime#177]
Hey, I was trying to use small time, but I didn't want to provide a actual "time" for my players, so I wanted to allow them just to see the sun and moon position, but seems like that option is not working.

It is a bug or something?

Small Time version: 1.16.6
Foundry version: 11.302

**Comment by unsoluble** [comment]
Seems to be working fine for me. Sure you're not just setting the default for new scenes, in settings?

**Comment by Alecell** [comment]
Wait I have to configure that per scene?
