### ISSUE TITLE
Incrementing Time Bounces Between Two Darkness Settings

### ISSUE THREAD

**Issue by MaverickH** [unsoluble/smalltime#179]
I am working on setting up my world to handle lowlight on roughly a half moon up to a full and back to half.

While I was trying to set it up, I was testing on a gibbous moon and found that whenever I incremented the darkness level changed dramatically back and forth every time I clicked an increment. The images show ten minute increments, but it did the same for the hour increments as well.

First it is dark enough that the low-light character cannot see the character outside of the firelight
![screengrab-dark](https://github.com/unsoluble/smalltime/assets/11905826/f329a060-583f-4730-aad0-a58aa5f669f2)

Move forward an increment, and the character to their right is now visible
![screengrab-light](https://github.com/unsoluble/smalltime/assets/11905826/e48d1e3b-066b-4cfa-bb51-787978002d79)

Move forward another increment, and they again lose sight of them
![screengrab-dark-2](https://github.com/unsoluble/smalltime/assets/11905826/1b751315-06d9-413e-91d6-6351f05be9a6)

I tried disabling Perfect Vision and found no effect. I did find that if I turned off the moon phase setting, it would make the issue only show up around dusk when it as changing from sunlight to moonlight.

Issue was found using Foundry 10 Version 302, but also was there after upgrading to Foundry 11 Version 306.

**Comment by unsoluble** [comment]
What game system? And are you running Simple Calendar?

**Comment by MaverickH** [comment]
I am running Simple Calendar and using PF2E

**Comment by unsoluble** [comment]
Make sure the PF2E darkness sync is disabled (in your world clock settings).

**Comment by MaverickH** [comment]
That did it, thanks much! Still having issues with getting tokens to "see" in that low-light stage during the gibbous stages, but that's on me. Closing and appreciate the quick response 💜

**Comment by MaverickH** [comment]
Problem resolved
