### ISSUE TITLE
[ENHANCEMENT] add a configurable keyboard shortcut to toggle smalltime widget (or a macro at least)

### ISSUE THREAD

**Issue by davelacorneille** [unsoluble/smalltime#181]
Thank you for this invaluable tool for my game! :)

I really would like to be able to toggle the widget more easily than having to go to note layer and click the button.

Also, one of my problem (maybe because I use foundry on different screen size and resolution), the widget is often under the macro bar or under something else and I'm having difficulties to access it.  With the toggle key, I would place the widget more in the center of the map to play with it when I need it and dismiss it right after.

**Comment by unsoluble** [comment]
Not a bad idea, could probably do that. :)

**Comment by unsoluble** [comment]
Added in 1.17.0 (default is Shift + S).

**Comment by davelacorneille** [comment]
Thank you works like a charm! :)
