### ISSUE TITLE
Please change the default "Visibility Toggle" Keybind to something else

### ISSUE THREAD

**Issue by GambetTV** [unsoluble/smalltime#183]
Shift + S is the default, which interferes with core Foundry keybinds. Shift + WASD rotates tokens facing, and this functionality cannot be rebound. It should be something else, or perhaps have no default keybinding, just so it doesn't wind up messing people up.

**Comment by unsoluble** [comment]
Almost anything is going to conflict with _something_. Do you have a suggestion for one that doesn't? Feel like the answer is just that people can rebind if needed.

**Comment by GambetTV** [comment]
I feel you, I just think overlapping it with something from Core that we can't rebind in Core pretty much means a lot of people will need to rebind it. Shift + L has no conflicts in Core, and I'm running 100+ modules for DnD5e and it doesn't seem to have any conflicts with any of them either.

**Comment by unsoluble** [comment]
Sure, except L doesn't make any intuitive sense for a SmallTime shortcut. I'll think about this a bit.
