### ISSUE TITLE
Darkness Level bug.

### ISSUE THREAD

**Issue by quantiq** [unsoluble/smalltime#186]
Darkness Level not adjusting as intended. At night should be 1.

![ST](https://github.com/unsoluble/smalltime/assets/51089209/73ecbe4d-1259-4dc0-b6a6-b834ce8d3f61)

**Comment by unsoluble** [comment]
What is your maximum Darkness level set to in SmallTime's settings? And do you have Moon Phase Affects Darkness enabled?

**Comment by quantiq** [comment]
I think is because of 4K resolution? It seams the settings are bugged in 3840x2160 resolution as you can see in the video.
https://streamable.com/3ackp2

**Comment by unsoluble** [comment]
Try with all other modules disabled?

**Comment by quantiq** [comment]
Same. The last version that worked was 1.16. something. I don't remember exactly.

**Comment by unsoluble** [comment]
Can't really recommend much, as I can't reproduce the behaviour and nobody else has reported it. Try Shift-clicking the Darkness Configuration header to reset those to defaults.

**Comment by quantiq** [comment]
I deleted and reinstalled the module. Same behavior but if I disable "Moon phase affects darkness" it works.

**Comment by unsoluble** [comment]
Well, that's what that feature is meant to do, so makes sense.
