### ISSUE TITLE
Reset position macro? 

### ISSUE THREAD

**Issue by ctbritt** [unsoluble/smalltime#187]
Is there a way to reset the position of the smalltime window via macro? I switch between my desktop and my laptop, and the screens are very different sizes. On the laptop, that means the ST window sometimes gets stuck behind the player listing and I can't change its location. Is there a way to reset its position when something like this happens?

**Comment by unsoluble** [comment]
Settings > Shift-click the Resting Opacity header.

**Comment by 8bitjunkie** [comment]
Does not work for players - GM only.

**Comment by unsoluble** [comment]
Good catch! Fixed in 1.22.0 :)

**Comment by 8bitjunkie** [comment]
Thank you!! 😊
