### ISSUE TITLE
Phase Impact per Moon for multiple moons

### ISSUE THREAD

**Issue by Peach774** [unsoluble/smalltime#188]
Now that phase impact is a feature, it would be nice to be able to configure phase impact for each moon, so for example a dim moon might not affect darkness very much (phase impact 0.1) and a normal moon would affect darkness as normal (0.4) such that when both are full, it would be combined based on their phases (0.5 if both are full).

If this isn't possible, it would be nice to at least be able to change which specific moon affects the brightness or disable a specific moon affecting brightness

**Comment by unsoluble** [comment]
Sorry, I'm not going to support more than one moon; too complex.

**Comment by Peach774** [comment]
> Sorry, I'm not going to support more than one moon; too complex.

But lighting level ALREADY is changed by multiple moons. If its able to take into account more than one moon, why can't it have phase impact for more than one?

**Comment by unsoluble** [comment]
SmallTime has no awareness of anything past the first moon.

**Comment by Peach774** [comment]
> SmallTime has no awareness of anything past the first moon.

https://github.com/unsoluble/smalltime/pull/169 this says that the lighting from multiple moons is used.

**Comment by unsoluble** [comment]
Ah, lol, that's what I get for accepting PRs; their code isn't in my mental model of the project. :)

But still that specifically is only related to the Global Illumination Threshold adjustment, doesn't touch the brightness-modifying code.

**Comment by Peach774** [comment]
> Ah, lol, that's what I get for accepting PRs; their code isn't in my mental model of the project. :)
> 
> But still that specifically is only related to the Global Illumination Threshold adjustment, doesn't touch the brightness-modifying code.

Would it be possible to at least add an option for disabling the brightness from any moons PAST the first if you can't add phase impact for other moons?

**Comment by unsoluble** [comment]
I don't know what you mean — brightness from any moons past the first have no impact on the global Darkness level currently.

**Comment by Peach774** [comment]
> I don't know what you mean — brightness from any moons past the first have no impact on the global Darkness level currently.

Am I misunderstanding the multiple moons brightness level thing from the PR? I thought if I have 2 full moons it would be brighter than if I have one. That certainly seems to be the case when I am playing.

**Comment by unsoluble** [comment]
That PR averages the phase-brightness values from all moons for specifically the Global Illumination Threshold adjustment feature (which is called `Moonlight Adjustment`, and is in the scene config), which is an entirely different thing from the adjustments made to the Darkness level of scenes.

**Comment by Peach774** [comment]
> That PR averages the phase-brightness values from all moons for specifically the Global Illumination Threshold adjustment feature (which is called `Moonlight Adjustment`, and is in the scene config), which is an entirely different thing from the adjustments made to the Darkness level of scenes.

OH - so I'm dumb, gotcha

**Comment by unsoluble** [comment]
tbh the two features are easily confused, and there's probably a better way of reconciling the two. But they were added at different times, for different reasons, so here we are.
