### ISSUE TITLE
More Precise Phase Impact levels

### ISSUE THREAD

**Issue by Peach774** [unsoluble/smalltime#189]
Foundry darkness is in 0.05 level increments, but phase impact is in 0.1 increments. It would be nice if phase impact was adjusted at the same variable level as foundry lighting so you could have more control in how variable the phase increment is.

**Comment by unsoluble** [comment]
The Phase Impact value is a percentage applied as a multiplier to the effect the moon's phase has on the Darkness level. I think 10% increments will be fine here.
