### ISSUE TITLE
Darkness tinting

### ISSUE THREAD

**Issue by pavalanche** [unsoluble/smalltime#193]
"Moon Phase Affects Darkness" tinting is always on, don't matter if switch in general settings or map is set or not.
With “Phase Impact” is set to 1 there is no darkness tinting at all.
Working again after downgrading to 1.18.0

**Comment by unsoluble** [comment]
Yep, it is known (and tracked in #190). Thanks!

**Comment by pavalanche** [comment]
Absolutly same problem with v 1.19.1
Again downgrading to 1.18.0

**Comment by unsoluble** [comment]
Can you elaborate? I cannot reproduce this issue in 1.19.1.

**Comment by pavalanche** [comment]
I like the darkness control of smalltime a lot.
Many thank for this marvellous GM support tool.
So I want to have it active in nearly all scenes.
But I have no use for Moon phase tinting (world with 3 moons).
So trying the given option in the settings of having darkness control active, but moon phase tinting off.
But:
"Moon Phase Affects Darkness" tinting is always on, don't matter if switch in general settings or map or both are set or not!

Also from my understanding strange behaviour:
“Phase Impact” set to 0 there is still a moon phase tinting.
With “Phase Impact” is set to 1 there is no darkness tinting at all.

**Comment by pavalanche** [comment]
…???...
So you are at the moment not interested in making a setting possibility you programmed yourself working as described?!
Saing something like – will be fixed in future would have been ok.
Instead suggesting I should set the moon colour in an calendar module from another person (cause there is no setting for this in your module) to a colour that would make the showings in the calendar wrong?
Got it – thanks for the conversation.

**Comment by unsoluble** [comment]
Well I'm certainly not interested in helping *now*.
