### ISSUE TITLE
Moonlight adjustment can not be toggled

### ISSUE THREAD

**Issue by Peach774** [unsoluble/smalltime#194]
![image](https://github.com/unsoluble/smalltime/assets/5171184/6f46e333-996d-4fdd-969e-28ce82aa7e25)
the option is greyed out and can't be clicked. I'm using PF2e if that matters.

**Comment by unsoluble** [comment]
Is automatically disabled when you have rules-based vision on.

**Comment by Peach774** [comment]
> Is automatically disabled when you have rules-based vision on.

But pathinder2e ALWAYS has rules based vision. So you just can't use this feature with pf2e?

**Comment by unsoluble** [comment]
You can disable RBV if you'd like. But this feature is incompatible with it.
