### ISSUE TITLE
Smalltime has vanished?!

### ISSUE THREAD

**Issue by PhiliousFogsley** [unsoluble/smalltime#196]
This is probably something I'm doing wrong but my Smalltime bar has vanished from my screen? It's still an option under the lighting section for the scene but I just can't seem to get it to appear on screen? Any thoughts?
![smalltime](https://github.com/unsoluble/smalltime/assets/155894288/7e78cc76-c032-402d-8669-e0256e3a171c)

**Comment by unsoluble** [comment]
Have you tried turning it back on? 🙂 

![image](https://github.com/unsoluble/smalltime/assets/801582/aeac73e3-d303-48c0-a8af-c720856e35a7)

**Comment by PhiliousFogsley** [comment]
hahahaha... well don't I feel stupid now!! Thanks for the help - unsurprisingly, it's now back!
