### ISSUE TITLE
[FEATURE] Make Min/Max Darkness Settings Available

### ISSUE THREAD

**Issue by Larkinabout** [unsoluble/smalltime#197]
Please could the Min and Max Darkness settings be made available for easy changing. I had an issue where the Darkness Level would only go to 0.3 at midday in a particular world and it was because the Min Darkness had been set, I think, based on where the Darkness Level was set when I first enabled the module. Making the settings visible and editable would have allowed me to figure out and rectify the issue sooner. Many thanks.

**Comment by unsoluble** [comment]
Hi there! This has been a feature in SmallTime's settings for a number of years -- see the readme for details. :)

Afraid I'm not going to extend this to a per-scene setting, as that would involve major UI changes.

**Comment by Larkinabout** [comment]
Ah, yep, I scrolled back and forth past that numerous times, it's because of the fancy interface when my brain was expecting a box with a number in it!

Would you potentially accept the per-scene implementation as a pull request (assuming I found the time)?
