### ISSUE TITLE
widget disappears with A/V dock changes

### ISSUE THREAD

**Issue by ditzer252** [unsoluble/smalltime#199]
If Smalltime widget is anchored to the player list and then the A/V dock changes (e.g. a new player joins or the dock is minimized) then the widget disappears and has to be manually re-toggled on before it is visible again.

Using Foundry 11.315 and PF2e 5.12.7

**Comment by unsoluble** [comment]
This is not my experience at all. How about with no other modules enabled?

**Comment by unsoluble** [comment]
Oh, unless you've got your AV dock pinned to the _left_, in which case all bets are off — in that case you'd need to place your SmallTime window somewhere else.

**Comment by ditzer252** [comment]
Yes.  I keep my AV on the left.
________________________________

**Comment by unsoluble** [comment]
Yeah in that case I'm afraid you'll just need to find a different place for the SmallTime window.

**Comment by ditzer252** [comment]
OK - I'll either move the AV dock to the top or find new place for the SmallTime widget.  Thank you.
