### ISSUE TITLE
Date and Date of Week support

### ISSUE THREAD

**Issue by apoapostolov** [unsoluble/smalltime#2]
I am using SmallTime and Calendar/Weather, and I am looking to drop Calendar/Weather but I need the support for date/date of week. No need to add buttons for it, just a thin line that is optional (off by default) and allows to check the date. 

![image](https://user-images.githubusercontent.com/4083812/117349804-7d08b100-aeb4-11eb-9e23-e77c924b1c95.png)

**Comment by apoapostolov** [comment]
Closing since already implemented. Thanks, it is awesome UX even if took me a bit to find.

**Comment by unsoluble** [comment]
Yeah, if you're syncing with About Time, you can click the time text in the SmallTime window to pop down the date display. I suppose this could be mentioned somewhere other than just in one gif in the readme. :)
