### ISSUE TITLE
Too much wasted space when attached to Player List

### ISSUE THREAD

**Issue by apoapostolov** [unsoluble/smalltime#20]
Given that space is not used for anything (when showing the date the UI has pushed up) the distance between SmallTime and PlayerList can be slightly minimized.

![image](https://user-images.githubusercontent.com/4083812/117632022-83817c00-b185-11eb-82ea-ba5757914cc6.png)

**Comment by unsoluble** [comment]
Hmm. I kinda prefer it have a bit of room to breathe there, but I might be able to cut a pixel or two — will experiment.

**Comment by unsoluble** [comment]
Shaved off 5 pixels for you in https://github.com/unsoluble/smalltime/releases/tag/1.3.5 :)
