### ISSUE TITLE
"Insufficient user rights" message pops up when changing time...

### ISSUE THREAD

**Issue by miklam** [unsoluble/smalltime#203]
Whenever I change the time in the SmallTime interface, a message pops up for all the other players in Foundry.
"Insufficient user rights."

I've tried giving them trusted player access, which doesn't fix it. The message doesn't pop up in a scene without tokens, so it must somehow relate to their tokens.

Is this a bug or a user error?

**Comment by unsoluble** [comment]
Try with no other modules enabled; this should not be a SmallTime issue.

**Comment by miklam** [comment]
Sorry for my late reply! I should've done that before writing, my bad! I will test it out and see what might be causing the conflict! Thanks for your reply and this awesome mod!
