### ISSUE TITLE
request: Advance 24 hours

### ISSUE THREAD

**Issue by MarkPearce** [unsoluble/smalltime#205]
It would be great to be able to step forward an entire day.  Maybe shift click/alt click the big step arrow,

or add 1440 minutes as an option to the big step drop down. (or make it a field)

**Comment by unsoluble** [comment]
If your Long Step is on 360, it's just two Shift-clicks to advance a whole day... I'm fairly averse to continuing to add more options. :)

**Comment by MarkPearce** [comment]
On the other hand four days is…

**Comment by unsoluble** [comment]
If you're tracking days of the week, you must be using a separate calendaring system, so probably best to just use the interface for that when jumping multiple days.

**Comment by MarkPearce** [comment]
no worries.  it's trivial change to make, i just didn't want to fork it if you were open to adding it. Thanks for the useful mod.
