### ISSUE TITLE
Best practice for Moonrise and Set times?

### ISSUE THREAD

**Issue by Taliesin1** [unsoluble/smalltime#206]
This is an awesome module. A a newbie to Foundry I love this so much. 

Is there a best practice for determining the rising and setting of the moon in Settings? Sunrise and sunset is easy enough, but the moon is tricky because it's not tied to the sun‘s timing. So how does one go about setting these?

**Comment by unsoluble** [comment]
SmallTime has no interaction or data related to moonrise/set.

**Comment by Taliesin1** [comment]
What are the little moon controls in settings that you can drag around? How are they used?

**Comment by unsoluble** [comment]
As described in that window, they're for setting the extents of sunrise/set, and for setting the maximum Darkness level.
