### ISSUE TITLE
Small Time display hidden by player list (only for GM)

### ISSUE THREAD

**Issue by devteamplus** [unsoluble/smalltime#208]
As you can see in this image, I cannot get to the Small Time interface because it is hidden behind the Player List.  My Assistant GM and other regular players see it above the Player List.  It's only my view that is like this.  I tried removing and reinstalling the module.

![image](https://github.com/user-attachments/assets/5ce8193c-d519-4f6d-97cb-714b04f09745)

FVTT v12.330
DND 5e v3.3.1

**Comment by unsoluble** [comment]
Shift-click the Resting Opacity header in the settings.

**Comment by devteamplus** [comment]
> Shift-click the Resting Opacity header in the settings.

Bingo!  Thank you!
