### ISSUE TITLE
Settings Menu doesn't compress properly

### ISSUE THREAD

**Issue by Peach774** [unsoluble/smalltime#209]
With the newest version - 1.20.3, the settings menu doesn't compress properly which can lead to other settings being off-menu when you are in the "all" section of settings menu.
![image](https://github.com/user-attachments/assets/3819e79a-93ac-4410-bb3c-82c93c301208)
Smalltime settings - small setting window.
![image](https://github.com/user-attachments/assets/188fcbab-42fe-4b0e-9e66-3f9e72520f8e)
Core settings - small setting window.
![image](https://github.com/user-attachments/assets/33598ca2-3607-4681-a0ed-c7f30c797517)
All settings - small setting window.
You can see the problem above.

**Comment by unsoluble** [comment]
Fair note, but honestly it's not a thing I'm going to accommodate unless I do a total rewrite. The CSS in that window is an absolute nightmare.
