### ISSUE TITLE
[Request] Hide interface

### ISSUE THREAD

**Issue by CaosFR** [unsoluble/smalltime#211]
Hello,

Thanks for your great module that you've been keeping up to date for a while.

I use the “Small Calendar” module in compact mode. I use it to manage the weather (with the “Simple Weather” module) and your module for dynamic lighting.

As a result, the Small Time interface is useless to me. I'd like to know if it's possible to implement an option to completely hide its interface (not just set its opacity when not hovering).

With CSS and a “display: none” it works in some case, but it's not too clean.

Thanks

**Comment by unsoluble** [comment]
Take a look at the readme. :)

**Comment by CaosFR** [comment]
"There's a show/hide toggle in the Journal Notes tool layer:" OMG :)

Sorry
