### ISSUE TITLE
Clock out of sync with simple calendar by exactly 1 minute

### ISSUE THREAD

**Issue by Cthoodles** [unsoluble/smalltime#212]
Just a weird bug I'm encountering, and searching through the settings didn't turn up a solution. I've got Simple Calendar installed, and I just installed SmallTime today. For some reason the SmallTime clock is always 1 minute ahead of the Simple Calendar clock no matter what I set the time to. PF2e's built-in world clock agrees with the Simple Calendar time.

![image](https://github.com/user-attachments/assets/a91736aa-73ce-4fb3-b9e3-14381cd75879)

**Comment by unsoluble** [comment]
Known issue when you're in a PF2e world with a date that's prior to the world's epoch. Nothing I can do (or rather, am interested in doing) about that, sorry.

**Comment by Cthoodles** [comment]
ah, damn. thanks for the quick response. What exactly do you mean by prior to the world's epoch? Like, if the date is from before the foundry world was created?

**Comment by unsoluble** [comment]
When you create a PF2e world, it has an epoch date set. I don't really understand their mechanics around it. But if your date in the world is at any point earlier than this epoch date, there's an off-by-one error that gets introduced somewhere in the calculation chain that I've never been able to track down.

**Comment by Cthoodles** [comment]
gotcha, that makes sense, thanks. Any chance you know how to change the epoch date in the world? If not I'll just ask around on discord and that should work. Thanks!

**Comment by unsoluble** [comment]
Pretty sure the short answer is you don't, but you could ask your system folks yeah.

**Comment by Cthoodles** [comment]
Managed to figure it out, actually! Had to go into the console, but `game.settings.get("pf2e", "worldClock.worldCreatedOn")` output the epoch date, and then `game.settings.set("pf2e", "worldClock.worldCreatedOn, [new date]")` let me change it. [new date] being the output of the first command but just changing the year number from 2024 to 2019
