### ISSUE TITLE
Time off when sync'd with World Clock or Simple Calendar

### ISSUE THREAD

**Issue by ottyn** [unsoluble/smalltime#213]
Foundry 12.331
PF2e 6.5.1
Smalltime 1.22.0

I have tried having the time source as both the PF2e and Simple Calendar.  Both show the same time on their respective clocks down to the second, but the Smalltime clock is a constant 1 min 1 sec ahead.

![image](https://github.com/user-attachments/assets/5063bc6b-9034-4a81-972f-e2dcb5275ef6)

**Comment by unsoluble** [comment]
See #212
