### ISSUE TITLE
[BUG] Setting menu console error

### ISSUE THREAD

**Issue by ottyn** [unsoluble/smalltime#219]
If you create a new world and do not have a scene created yet, you will get the following error message in the console when you open the Configure Settings menu with SmallTime enabled.  The Darkness Configuration setting in SmallTime is missing it's image until a scene is created.  Once you create a scene, the error does not appear and the SmallTime clock will appear.  The background image in the Darkness Configuration setting will also appear.

FVTT 12.331
SmallTime 1.24.0

![image](https://github.com/user-attachments/assets/97782036-3886-43dc-9b94-48c6f1ce71d1)

**Comment by unsoluble** [comment]
Thanks for the report, but not concerned about this. :)
