### ISSUE TITLE
Simple Calendar Implementation

### ISSUE THREAD

**Issue by Bolt7** [unsoluble/smalltime#23]
Simple Calendar's custom time settings let you pick hour/day minute/hour and second/minute numbers. Being able to use that module's time using it's custom units would make them a fantastic module pair.

**Comment by unsoluble** [comment]
Have you hit the Export to About Time button yet, in SC's config screen?

**Comment by unsoluble** [comment]
Ah, okay, apologies, that was just a complete mis-read of your original post it seems. In that case I'm afraid the answer is no, that almost certainly isn't going to happen. Just way too much complexity for this single-purpose module.

**Comment by Bolt7** [comment]
That's a shame, but understandable.

**Comment by unsoluble** [comment]
You're more than welcome to fork! :)

**Comment by Bolt7** [comment]
Sadly I don't know how to code in situations out of Khan Academy's Javascript Course and basic Python.
