### ISSUE TITLE
One month delay from Simple Calendar to Small Time

### ISSUE THREAD

**Issue by JhaelenTerear** [unsoluble/smalltime#29]
Hi,

When I used both these modules, all is great except the month displayed in Small Time isn't the good one.
![1](https://user-images.githubusercontent.com/58259514/118513444-01202b80-b734-11eb-839d-c76e8130ca89.jpg)
![2](https://user-images.githubusercontent.com/58259514/118513485-0aa99380-b734-11eb-8d5c-7f2ed8e31e4f.jpg)

**Comment by unsoluble** [comment]
Looks like your Simple Calendar isn't quite in sync with About Time (which is what provides the date to SmallTime). Try hitting the Configure button there, and click the Export to About Time button, and make sure your sync type is set to "Mixed".

**Comment by JhaelenTerear** [comment]
Thanks for your response. I already done that multiple time, before creating this issue. I'm going to make another tests.

**Comment by Eonfuzz** [comment]
Hey, we're running into this same issue.
Did you ever find a fix?

**Comment by JhaelenTerear** [comment]
No, I didn't. If you find one, I'm interested because it's annoying 😉.

**Comment by unsoluble** [comment]
Hmm. I still can't get this behaviour to happen on my end. Can either of you determine a set of steps to reproduce this offset?

**Comment by unsoluble** [comment]
Interesting. I'll throw a ping at Tim, see what he thinks.

**Comment by Eonfuzz** [comment]
It could be some timezone weirdness. I hate timezones.
We're using non-american date, so that's DAY/MONTH/YEAR.

Could that be the source of our woes?

**Comment by tposney** [comment]
I think this might be falling afoul of the new about time offset field - which is meant for non-standard world times. Make sure the about-time setting is blank.

**Comment by venom986** [comment]
There was also a bug in Simple Calendar that the author just fixed yesterday. It caused about a month discrepancy between Simple Calendar and About-Time (which would show up in SmallTime since it's just displaying About-Time's time).

**Comment by unsoluble** [comment]
Thanks for the help tracking this one down, everyone. Think we'll call it closed at this point.
