### ISSUE TITLE
Reset to Default button for the new fancy sunrise/sunset slider UI

### ISSUE THREAD

**Issue by apoapostolov** [unsoluble/smalltime#31]
It's great to be able to change this for many campaigns that depend on it (such as Icewind Dale) but a reset button would be greatly appreciated rather than remember default values or use new world to get the,.

**Comment by unsoluble** [comment]
Hmm, I'll think about that one, thanks.

**Comment by unsoluble** [comment]
Check out 1.6.8. :)

![CleanShot 2021-05-23 at 15 42 59](https://user-images.githubusercontent.com/801582/119279003-da537080-bbdd-11eb-8650-2e9bae27880f.png)
