### ISSUE TITLE
smalltime always starts in realtime mode

### ISSUE THREAD

**Issue by Drental** [unsoluble/smalltime#33]
When I load up my world where I recently added this module the time is always moving forward until I shift-click the clock. This is especially weird since the world is still paused and About Time is set to a real time interval of 0 (aka no real time advancement) and there is an active combat going on at this moment in the world in question.

Setting the game time update multiplier in About time stops the clock from advancing but I like having the option to advance the world time naturally during RP Parts.

(I play PF2e and there are time limited effects so this can affect encounter balance if it's not noticed.)

**Comment by unsoluble** [comment]
Weird! I'll try to track this down today, put in a check to make sure it doesn't happen.

**Comment by unsoluble** [comment]
Far as I can determine, this appears to be a one-off glitch with About Time in that particular world; can't repro, and have put in some failsafes in ST just in case.
