### ISSUE TITLE
Expand upwards

### ISSUE THREAD

**Issue by rmasoni** [unsoluble/smalltime#34]
When you show the date by clicking the time, it expands downwards, hiding the move handle behind the player list when the windows is docked. It should expand upwards.

**Comment by rmasoni** [comment]
After a refresh, I clicked again and it expanded upwards. Must be some edge case. Not sure why it expanded downwards before.

**Comment by unsoluble** [comment]
Yeah, there are indeed a couple of rare edge case scenarios you can get the window into, where it won't know that it's in the pinned location until a refresh. I'll try to harden that a bit, but it shouldn't happen most of the time. :)
