### ISSUE TITLE
Hide the time

### ISSUE THREAD

**Issue by rmasoni** [unsoluble/smalltime#35]
I don't want my players to know exactly what time it is, so only having the sky showing for them would more adequately translate what their characters see and know (there are basically no clocks in the world).

**Comment by unsoluble** [comment]
Hmmm, this is a good suggestion, I can see where it'd be useful to have the ambiguity. Also I think it probably makes more sense to have the "can players see the sun and/or time" control be scene-specific, to account for underground scenes etc. Gonna think this through, might rework things a bit.

**Comment by unsoluble** [comment]
Implemented in 1.7.0 :)
