### ISSUE TITLE
Darkness value error when moving the sun/moon

### ISSUE THREAD

**Issue by YugoNumachi** [unsoluble/smalltime#38]
When moving the sun/moon when the darkness level of the scene is linked to SmallTime, it generates value errors for Darkness

![image](https://user-images.githubusercontent.com/83497401/120063724-d9e92880-c068-11eb-97cc-d08deb81a37d.png)

**Comment by unsoluble** [comment]
What version of SmallTime is this? There was a fix for this particular thing in 1.6.9.

**Comment by unsoluble** [comment]
If you're on 1.6.9 or later already, going into the darkness config and moving a sun a bit and saving should clear it up from then on.

**Comment by YugoNumachi** [comment]
1.7.0, I moved the sun in the module config, but same thing.
I get errors with 1.1 and -0.1

**Comment by YugoNumachi** [comment]
And I tried to move one of the moons, and now SmallTime does nothing anymore...

**Comment by YugoNumachi** [comment]
Playing with the scene darkness in the scene config apparently solved it altogether.
The solution path was not that obvious though.

**Comment by unsoluble** [comment]
Thanks for the report, though! I've added in even more clamping protections for those values. :)
