### ISSUE TITLE
Feature Request: Allow players to display date when visibility is set to "Sun/Moon position only"

### ISSUE THREAD

**Issue by marcstraube** [unsoluble/smalltime#40]
Hi, I just found your module through Simple Calendar and am experimenting for a bit. If I set the visibility to "Sun/Moon position only", the players can't display the current date. It would be nice to have an additional option for this.

**Comment by unsoluble** [comment]
While I appreciate that there may be cases where one wants players to be able to see the date but _not_ the time, I'm really not into adding a second tier of options to control this (and the UI for toggling would need re-thinking).

Probably not going to happen, but I'll think about it for a while. :)

**Comment by rmasoni** [comment]
Oh, I haven't got time yet to fully test SmallTime since the update that introduced this feature. I thought it was only hiding the time and not the date. Please consider having it three ways: only sun/moon, only sun/moon with date, everything.

**Comment by DarKDinDoN** [comment]
I second @rmasoni comment.
I would really like to show the date to my players, but not the time.

**Comment by unsoluble** [comment]
> And since it's a wishlist, not having to shift click to make the current day visible (visible by default)

Not sure what you mean there — Shift-click starts the realtime clock, and if you have the date toggled visible it should be remembering this state already.

**Comment by DarKDinDoN** [comment]
> > And since it's a wishlist, not having to shift click to make the current day visible (visible by default)
> 
> Not sure what you mean there — Shift-click starts the realtime clock, and if you have the date toggled visible it should be remembering this state already.

I meant, not having to do that. But that's really just a minor upgrade.

**Comment by unsoluble** [comment]
I think requiring people to make one click to show the date and then never having to do this again isn't too much to ask; not going to make the date always show by default, as that defeats the "small" part of SmallTime. :)

**Comment by DarKDinDoN** [comment]
> I think requiring people to make one click to show the date and then never having to do this again isn't too much to ask; not going to make the date always show by default, as that defeats the "small" part of SmallTime. :)

Sounds reasonable. Agreed.

**Comment by unsoluble** [comment]
Have revisited this a few times now, and it's just going to be too much effort for very little gain. Going to wontfix this one for now.
