### ISSUE TITLE
Visibility control isn't working

### ISSUE THREAD

**Issue by rmasoni** [unsoluble/smalltime#43]
The option to only show sun/moon or nothing at all doesn't seem to be working. With either selected, players can still see SmallTime in its entirety.

**Comment by unsoluble** [comment]
Hmm! Foundry and game system versions?

Also are you changing the visibility setting in the _scene_ config, or just in the module settings screen? (The latter only sets your default for new scenes.)

**Comment by rmasoni** [comment]
Oh, that was it! I was setting it in the module settings, not in the scene config. Maybe it could be made a bit more clear in the help texts to avoid confusion?

**Comment by unsoluble** [comment]
Ah, glad you sorted it. I'll think about whether the messaging could be clearer there.

**Comment by unsoluble** [comment]
Changed how this works in 1.7.2 — hope it makes more sense now. :)
