### ISSUE TITLE
Breaking Player Configuration

### ISSUE THREAD

**Issue by aruguy** [unsoluble/smalltime#44]
I've narrowed it down to this module:
With SmallTime enabled, whenever I click on the 'Configure Players' button under 'Game Settings', I get an error and I'm returned to the /join page instead of /players.

**Comment by unsoluble** [comment]
Weird! Can you screenshot the error for me? What Foundry and SmallTime versions?

**Comment by unsoluble** [comment]
Can't reproduce, no further info provided; closing for now.
