### ISSUE TITLE
Hours difference between SmallTime and AboutTime

### ISSUE THREAD

**Issue by apoapostolov** [unsoluble/smalltime#47]
In PF2, FVTT 0.8.6, I finally managed to sync SimpleCalendar and AboutTime to sync properly together. 

Unfortunately as result this caused a ongoing hour discrepancy between SmallTime and AboutTime, as seen below

I have tried to modify game clock but there seems to be hard 3 hours difference now. A setting to fix such desync by moving SmallTime -X hours, could potentially allow to fix this when it happens. 

![image](https://user-images.githubusercontent.com/4083812/121401363-503b3400-c961-11eb-8b61-03712c4960dc.png)

**Comment by unsoluble** [comment]
What does the actual About Time clock show in that case? (via `Gametime.showClock();`)

**Comment by apoapostolov** [comment]
![image](https://user-images.githubusercontent.com/4083812/121403382-82e62c00-c963-11eb-84ee-9f5083349a32.png)

It seems not a SmallTime issue. Maybe a SmallCalendar or AboutTime issue?

A setting to fix that when it occurs would be nice to have, but I understand if this is something to be brought to other people's attention.

**Comment by unsoluble** [comment]
Yeah as far as I can tell, SmallTime will _always_ be in sync with About Time. Whether or not _that_ stays in sync with other time stuff is a separate issue — I know both Tim and @vigorator (SC) have been working through a number of challenges here, especially in the PF2 context.

**Comment by apoapostolov** [comment]
@unsoluble Just to let you know 1.8.3 resolved this issue, it is now perfectly in sync.
