### ISSUE TITLE
On a scene where smalltime sets darkness, darkness alternates light/dark between time changes

### ISSUE THREAD

**Issue by apoapostolov** [unsoluble/smalltime#48]
How I reproduce it:
- Set time to darkness via SmallTime
- Set a scene to SmallTime Darkness ON
- Make a combat and start moving rounds
- When the time proceeds to next turn, the scene will become daylight
- As rounds proceed daylight gets back to darkness, then back to daylight, then to darkness

If you start moving the clock on Smalltime back while stuck to daylight, some hours will change to darkness but then change to daylight again. 

https://streamable.com/vdhjv5

**Comment by unsoluble** [comment]
Can't reproduce this in a world with just SmallTime and About Time, under 0.7.10 (will try 0.8.6 when I get a chance later tonight).

**Comment by unsoluble** [comment]
Yeah, can't repro in 0.8.6 either; I think one of your other modules is interacting with things there.

**Comment by apoapostolov** [comment]
I can confirm that this is not a mod conflict. 

In the video I am using Culprit to have only AboutTime and SmallTime running. 
https://streamable.com/2ijpnr

I can also export the world for you:
https://we.tl/t-g9uWm9TsDZ

**Comment by unsoluble** [comment]
Ah. Thanks, having the world helped — it's the Synchronize Darkness setting in the PF2 world clock config. I have no idea what that's doing behind the scenes, but having it on causes this behaviour, and it's fine with it off.

**Comment by apoapostolov** [comment]
It is probably trying to do the same thing as SmallTime. Thank you very much for finding that out. Turned it off and all is good now.
