### ISSUE TITLE
Add support for custom darkness times

### ISSUE THREAD

**Issue by flamewave000** [unsoluble/smalltime#5]
Depending on the season/location the campaign is running in, a DM may want to change the times that darkness begins to set (in northern winters, the sunset starts around 4:30p and sunrise starts around 7am, with only about 8 hours of daylight)

**Comment by unsoluble** [comment]
Yep, that one's been on my "eventual" list for a while now, just need to work out the best way to implement the UI for making these changes.

**Comment by flamewave000** [comment]
You could register a menu in settings that could also be displayed when the user double clicks the "time" string on the clock. Then you could use `<input type="time">` to have the browser handle the UI for you.

**Comment by unsoluble** [comment]
Yeahhhh having the browser handle the UI is basically the antithesis of the module's purpose, so I'll get back to you on that. ;)

**Comment by unsoluble** [comment]
Implemented in 1.6.0 :)
