### ISSUE TITLE
Slight visual issue - SmallTime does not render on the first scene when a world is loaded

### ISSUE THREAD

**Issue by apoapostolov** [unsoluble/smalltime#51]
The video demonstrates the issue: https://streamable.com/3vos2e

**Comment by unsoluble** [comment]
Yep, I think I've already fixed that one.

If you want to give it a shot before I get a chance to push another release, replace your `/modules/smalltime/scripts/smalltime,js` with this: https://raw.githubusercontent.com/unsoluble/smalltime/main/scripts/smalltime.js

**Comment by unsoluble** [comment]
Should be fixed in 1.8.5
