### ISSUE TITLE
1.8.5 introduced 1 day discrepancy with Gameclock, PF2, SimpleCalendar

### ISSUE THREAD

**Issue by apoapostolov** [unsoluble/smalltime#52]
The issue wasn't present in 1.8.4

![image](https://user-images.githubusercontent.com/4083812/121950311-1f447000-cd62-11eb-82cb-fa57f78a6b40.png)

**Comment by unsoluble** [comment]
Known display bug in SC. The date is correct, but it's displayed wrong in the SC window.

**Comment by unsoluble** [comment]
Yeah I'm gonna need to wait on SC to clear up some confusion around the date-getter API. Will keep you posted.

**Comment by unsoluble** [comment]
Should be fixed as of 1.8.6 — lemme know if not!

**Comment by apoapostolov** [comment]
Yes fixed now, along with the latest SimpleCalendar update.
