### ISSUE TITLE
smalltime always advancing the day on drag

### ISSUE THREAD

**Issue by Drental** [unsoluble/smalltime#55]
Hi unsol,

every time I change the time in my world by dragging the slider small time advances by a day.

the buttons on the bottom are moving the date in the expected but time in the wrong direction.

The world clock is missing a minute every time.

Modules: About time

System: pf2e

I can give you access to a world where this is happening, you know who I am :)

**Comment by unsoluble** [comment]
Heya. I'm assuming latest versions of everything? I think we're pretty in sync with both AT and PF2 now, can't repro this. Thing to try: Make a note of your current date/time if it's important to you, then in the PF2 clock settings screen hit the reset button. See if things sync up after that.

**Comment by Drental** [comment]
just updated, so yeah. will try that after my game today.

**Comment by Drental** [comment]
Got back to it.

The issue appears when you move the world time to the past. (just advance backwards a bit in a new world and see the magic)

*insert :stress:*

**Comment by unsoluble** [comment]
Okay, I'm seeing _something_ here, but want to clarify:

If the current time is _earlier_ than the world-start date, dragging the sun/moon still sets the time as expected, and the date remains accurate, but the _decrement buttons_ work backwards — they only advance the time. That's what I'm able to reproduce here, but I don't see any of the other things in your original post.

**Comment by unsoluble** [comment]
Fixed the increment/decrement buttons in pre-epoch times in 1.8.8 — hope that clears this up, lemme know if there's still some other buggy aspect here.
