### ISSUE TITLE
[FEATURE REQUEST] implement new Simple Calendar options Trough API

### ISSUE THREAD

**Issue by DarKDinDoN** [unsoluble/smalltime#59]
Hello,

SimpleCalendar just updated its API with more data.

![image](https://user-images.githubusercontent.com/1687854/123399065-79380780-d5a4-11eb-9b91-0bdc8df7a694.png)

It would be very nice if  smalltime could handle this new set of data:
- Year prefix: display before year with space (if not null or empty)
- Year postfix: display after year with space (if not null or empty)
- Season: display somewhere near the date (if not null or empty)
- Season object also returns a color code: might be cool to have that somewhere in smalltime as well.
- Show the weekday heading: if false, smalltime shouldn't display the weekdays (monday, tuesday, etc..), and remove the comma before the date/month

Thx!

**Comment by unsoluble** [comment]
Thanks for the heads-up. The way the date-display stuff is currently designed, I need to have the same formatting options available to _all_ calendar providers; giving bespoke options for SC would take a bit of a refactor here. Will consider it tho. :)

**Comment by DarKDinDoN** [comment]
@unsoluble I believe that SimpleCalendar updated its API to fix a bug regarding days offset.
The new property to display the day number is "dayDisplay".

Reason: this bug fix on SimpleCalendar repo: https://github.com/vigoren/foundryvtt-simple-calendar/issues/145

**Comment by DarKDinDoN** [comment]
@unsoluble attempting to solve that issue while keeping things simple: https://github.com/unsoluble/smalltime/pull/62
Either others calendars provide the data of the relevant piece of data is not displayed.
