### ISSUE TITLE
User Lacks permission to update the world setting smalltime.calendar-provider

### ISSUE THREAD

**Issue by foxreinhold** [unsoluble/smalltime#61]
With the latest update on 0.7.10 my players are getting this message on login.  Does not seem to affect anything from what I can tell, but I figured I'd report it.

https://cdn.discordapp.com/attachments/724144752437493811/859276222785912852/unknown.png

Downgrading to 1.8.8 removed the issue (as that was the previous version I was on, I believe.

**Comment by unsoluble** [comment]
Ah, thanks for the report. I know what's happening there, just won't get a chance to fix it until tomorrow afternoon sometime.

**Comment by foxreinhold** [comment]
Yes, 1.9.6 appears to have fixed the thing. :P
