### ISSUE TITLE
Players cannot see Smalltime at all, no matter what GM settings I use

### ISSUE THREAD

**Issue by TheOneAndOnlyPhane** [unsoluble/smalltime#66]
As the title suggests, my players can't see **Smalltime** in the game. I've tried playing with all the player visibility settings and they don't seem to change anything.

**Comment by unsoluble** [comment]
Have your players tried clicking the visibility toggle?

https://github.com/unsoluble/smalltime/blob/main/doc/Toggle_Control.png?raw=true

**Comment by TheOneAndOnlyPhane** [comment]
As far as I can tell, they do not see the visibility toggle either. I've tested on multiple users with different permissions settings for my players.

![image](https://user-images.githubusercontent.com/22590161/125279001-16709b00-e31c-11eb-9477-70a5c0e5a6a4.png)

**Comment by unsoluble** [comment]
Hmm. So `Player Visibility` in the scene's config is set to something other than `Nothing`? Any errors in the console (F12) on the player end on a refresh? What game system? Does this happen in any other worlds?

**Comment by theripper93** [comment]
seems that if in the scene is not set to "default" it won't be visible

**Comment by unsoluble** [comment]
Can either of you provide repro steps? I can't get this to not work as intended.

**Comment by theripper93** [comment]
it seems that if the flag for the scene has not been set yet it counts as off

**Comment by unsoluble** [comment]
Mkay, try 1.10.1.

**Comment by theripper93** [comment]
yep it's fixed

**Comment by unsoluble** [comment]
Nice, thanks for the assist!
