### ISSUE TITLE
Custom Offset for Smalltime window when Docked

### ISSUE THREAD

**Issue by JamzTheMan** [unsoluble/smalltime#68]
Is it possible to add a setting to let user add a x/y offset to use when the small time window is snapped/docked to the bottom left Players window? When using custom UI mods, the window docks to low.

![image](https://user-images.githubusercontent.com/8051654/126225092-35033a4f-78bc-4d67-b652-9acac13b56bd.png)

**Comment by unsoluble** [comment]
So far I've just been hardcoding offsets for systems that change the Players window. Is that the stock PF1e system there? Or is it a module on top?

**Comment by unsoluble** [comment]
Appears to be a module involved.
