### ISSUE TITLE
Position Reseting when Full Screen is toggled

### ISSUE THREAD

**Issue by DivertedCircle** [unsoluble/smalltime#70]
Using Firefox, I'm finding that if I put the display at the bottom of my screen it will get shunted upwards and stay there when I toggle between full screen.

**Comment by unsoluble** [comment]
Yeah that's an expected behaviour at this point; listening for and reacting to viewport changes is something I've toyed with but _so far_ it's been not worth the effort it would take to make it work right. May revisit if I get a larger chunk of dev time in the future.
