### ISSUE TITLE
Feature request - integrate start/stop button integrated with SimpleCalendar

### ISSUE THREAD

**Issue by scooper4711** [unsoluble/smalltime#71]
The simple calendar has a time start/stop button. It would be nice to have that function available in this UI.

**Comment by unsoluble** [comment]
Already there, just a little hidden — Shift-click the time. (It's in the readme! :) )

**Comment by scooper4711** [comment]
Then I think this becomes a bug report. 😄 
shift clicking does the same as just clicking - toggles the date.

**Comment by unsoluble** [comment]
Game needs to be unpaused for the realtime clock to be able to start. Is it?

**Comment by scooper4711** [comment]
Indeed it is unpaused. I'm able to start/stop the clock with the SimpleCalendar interface, but not with SmallTime. I can watch time progress in SmallTime when it's running in SimpleCalendar.
I doubt it matters, but I'm running the HarnMaster 3 game system.

**Comment by unsoluble** [comment]
Do you have About Time installed and enabled? That's also required for ST to use the realtime clock.

**Comment by scooper4711** [comment]
Ah - I thought Simple Calendar was a replacement/did the same function as About Time. 
Not sure I want to install it just for one small function. 
Thanks!

**Comment by unsoluble** [comment]
About Time is super low-profile — doesn't have any UI at all — so is "safe" to add. But that said, this does remind me that I can now remove the dependency on it for this feature and call into SC's real-time clock toggles instead. Will make that switch when I get a chance.

**Comment by unsoluble** [comment]
Just removed the reliance on About Time for this, in version 1.11.0 — can now toggle realtime with just Simple Calendar present.
