### ISSUE TITLE
Dragging/Clicking Sun/Moon advances a day

### ISSUE THREAD

**Issue by JamzTheMan** [unsoluble/smalltime#73]
Using the latest versions of Foundry/PF2E, no mods.

I just noticed if I adjust the time using the sun/moon slider, the clock advances a whole day. It happens if I drag or click in that bar and happens if I go forward or backward in time, it always advances 1 day.

This now explains why the lighting seems to go dark then bright then dark again sometimes. :)

![image](https://user-images.githubusercontent.com/8051654/129225092-54f7876d-e9ff-4aec-b914-35c8e5762eaa.png)

**Comment by unsoluble** [comment]
Ah yeah, this will happen if your PF2E world clock is messed up somehow. Take note of the current date if it matters, then open the PF clock controls, then settings, then reset the clock. Should behave as expected after that.
