### ISSUE TITLE
Small time location needs to be resettable

### ISSUE THREAD

**Issue by diannetea** [unsoluble/smalltime#74]
At some point this has disappeared from my GM account's window.  I checked opacity, it is set to 0.8 (also tried 1).  I've tried fullscreen (f11) and it is still not visible.  It IS on my player account screen, so it's working, but I have no idea where it went on the GM account and I do not see a way to reset position.

**Comment by unsoluble** [comment]
Have you checked the visibility toggle yet? (in the Journal Notes tool layer on the left)

If that doesn't work, try resetting the window's position by Shift-clicking the "Resting Opacity" label in the settings screen.
