### ISSUE TITLE
Feature Request - Changing sunrise/sunset

### ISSUE THREAD

**Issue by MapperD** [unsoluble/smalltime#75]
It would be nice to have the ability to set the sunrise and sunset time based on the day (not every day but maybe one or 2 key points in the month)/month/season.
Overcomplication would be to include latitude shift but lets not get crazy.

**Comment by unsoluble** [comment]
Yeah that's not going to be something that I'll add directly to SmallTime, _but_ I'm definitely going to incorporate it as an optional pull from Simple Calendar's API, if/when that module gets dynamic sunrise/sunset capability.

**Comment by MapperD** [comment]
Cool, wasn't sure which module would likely handle such a task so I thought I'd ask anyway.
