### ISSUE TITLE
Dragging/Clicking Sun/Moon advances a day

### ISSUE THREAD

**Issue by JamzTheMan** [unsoluble/smalltime#78]
I did as suggested per issue #73 BUT it only fixes it if the date is >= 02/12/4721

As soon as I advance back to 02/11/4721 or earlier, it advances a day again on click/drag until it reaches 02/12/4721.

On a brand new test world it was happening as soon as I went back 1 day after resetting the clock.  Is this not compatible with PF2E and dates older than today's date + 4700??

**Comment by unsoluble** [comment]
Ummmm weird. I'm not really sure what's going on there, but I'll dig into it when I've got a chance.

**Comment by unsoluble** [comment]
Sorry for the long turnaround, but this should be fixed in 1.11.4.
