### ISSUE TITLE
Feature Request: Time within user-specified ranges displays on the clock as 'text' instead of numbers.

### ISSUE THREAD

**Issue by ZebraMilk** [unsoluble/smalltime#79]
Hello! I love this module deeply. Thanks for your work.

I am wondering if it would be possible to set up an option where during certain times, the display would read something like "Morning" or "Night"?

Example:
Time is 4am-5:59 am, the in-game clock display reads "Early Morning"
Time is changed to between 6am and 8:59 am, the in-game clock displays "Morning".

I want to keep track of time and love the darkness control that comes with the slider, but I don't want my players to be so worried about the literal minutia. Maybe an option to display only to players?

**Comment by unsoluble** [comment]
Hi there! Glad to hear you're enjoying the module. :)

I think you might have missed the bit in scene config where you can set the player display to "Sun/Moon position only," which should provide the level of information you're looking for:
![CleanShot 2021-08-22 at 11 13 23](https://user-images.githubusercontent.com/801582/130365615-d813bf74-3264-4586-a89f-ec573412a7a8.png)

(Can also set a default value for that in SmallTime's settings, for new scenes going forward.)

**Comment by ZebraMilk** [comment]
I love that bit, but I am actually wondering if it's possible to add a text
to display. Thank you for responding!

**Comment by unsoluble** [comment]
Possible? Yes. Going to actually do it? Pretty sure no, sorry. :)

**Comment by ZebraMilk** [comment]
Haha! That's totally fine. It doesn't hurt to ask. Again, thanks for a
lovely module!

**Comment by unsoluble** [comment]
Never hurts to ask! Also don't forget the code is open licensed and free to fork any time, if you want to implement your own custom features. :)
