### ISSUE TITLE
[Suggestion] Add toggleable compact calendar display fed by Simple Cal

### ISSUE THREAD

**Issue by Shuggaloaf** [unsoluble/smalltime#80]
Hi Unsoluble,

Just made the switch to SmallTime. Really like the linked scene darkness and slider.  More importantly, I see how active you are and honestly I've talked to you everywhere from Reddit to Discord. In other words, I know this mod will be kept up to date and I appreciate that!

One thing I think would be immensely handy is a compact, toggleable month calendar. A toggle similar to your date field. I'm imagining a calendar that would basically just pull data from Simple Calendar and re-display it. No real controls or anything (beyond what you'd like to do of course).

Simple Cal works great for the in-depth stuff like setting up months/weeks/days, moon cycles as well as notes. Where it lacks is the UI is a bit clunky. Having a simple month view is mostly all I need 90% of the time. If I can pop that up with 1 mouse click on SmallTime, which I will already will have on-screen 100% of the time, would be ideal. 

Since a pic is worth 1000 words...
![ST_Alt](https://user-images.githubusercontent.com/79543184/132067961-1b91f04b-55a7-45da-9392-68746ddb35fb.jpg)

EDIT: 1 minute after posting I find the click date to open SC. Love this level of detail! If you are able to add the "bonus" buttons in my pic above, maybe this function could be moved to the notes badge, while the add note would open the SC new note window and clicking date would open the calendar. 

Thanks for your consideration and everything you provide for the community!

**Comment by unsoluble** [comment]
Hello! Thanks for the detailed writeup, and I'm glad you're liking SmallTime. :)

This one is tricky. I do agree with the premise entirely — that it'd be nice to have a unified UI for the calendar as well, if one is using SC. The problem I see is that this would make my code _very_ tied to SC's development, with so many hooks and interactions linked between the two — and to be honest I'm not really into having to track someone else's code that closely for the long haul.

Perhaps if at some point @vigoren designs a similarly-themed compact view on his end, I could just drop it in wholesale, but until then I think I'm going to have to put this one on the Not Terribly Likely pile. :)

**Comment by unsoluble** [comment]
> If you are able to add the "bonus" buttons in my pic above, maybe this function could be moved to the notes badge, while the add note would open the SC new note window and clicking date would open the calendar.
Problem with this is that the date itself can already often fill the entire div, and I don't even have a great overflow solution for that yet. More buttons just don't have anywhere great to go. I'll definitely have a think on it tho.

**Comment by vigoren** [comment]
I do plan on redoing Simple Calendars interface in the hopefully not to distant future. The new interface will hopefully meet the more compact views that some users want. This task has not been the highest priority as lots of people use this mod for its great features and interface.

@unsoluble that is an interesting idea. if I were to offer the ability to get the calendar view from my module how would you prefer to get it? From the API or would a handlebar helper be better (if possible I haven't tested using those between modules)

I also do not blame you for not wanting to follow another developers project that closely haha

**Comment by unsoluble** [comment]
> if I were to offer the ability to get the calendar view from my module how would you prefer to get it?

Good question! Not at all sure what the best way to go would be, never looked into something like this before. Perhaps if your month view was a standalone HTML template with handlebars, then I could include and style it? But I don't know how the JS interactions would work. Worth investigating though; we should try to minimize duplication of effort here.

**Comment by vigoren** [comment]
I agree we should reduce duplication.

I will set up a test and see if I can do the month view as a handlebar helper and use it in another module. That would be the simplest way to go I think.

**Comment by Shuggaloaf** [comment]
A lot of conversation while I was away, great!

>The problem I see is that this would make my code very tied to SC's development

A very valid point and one I hadn't considered. I was thinking/hoping there was an easy way to just "read" SC's data. However, it sounds like you and Vigoren are working towards something like that.

>More buttons just don't have anywhere great to go.

Just to clarify on this one, that "bonus" items was only if you were able to implement the collapsible month calendar view. Which I would guess gives you more room to work with. However I'm not a programmer s I may be completely misunderstanding. 

>Plan on redoing Simple Calendars interface... not the highest priority as lots of people use this mod for its great features and interface.

Yeah just to make sure you understand, I think the features and settings verbosity of SC is great! Not taking anything away from that. If I am actively modifying/setting up a calendar, I love the interface for doing so and would not want that to change. 
The always-on-the-screen interface, even in compact mode, could definitely use some work though. Please take this as a small constructive criticism, I'm not trying to bash your mod. :-) 


And finally, I appreciate both of you coming together and discussing possibilities. Even if it doesn't go anywhere, you guys are making the effort and it is much appreciated!

**Comment by unsoluble** [comment]
Very cool, looking forward to playing around with this.

**Comment by vigoren** [comment]
Well what a journey this has been. Starting this change lead me down writing and releasing version 2 of Simple calendar lol

With it live now I have more to share. I have added some handle bar helpers that generate this calendar view and basic interactivity. The full documentation for it can be found here https://simplecalendar.info/enums/HandlebarHelpers.html#sc_full_calendar

That should cover how to set it up and use the helper but if you have questions/suggestions please let me know!

**Comment by unsoluble** [comment]
Haha, you're... welcome? 🤣 

And thanks for the helper and info, now I just need to not be super busy some weekend to sit down and poke at it some.

**Comment by Shuggaloaf** [comment]
@vigoren @unsoluble 

I am very glad I could be the catalyst of ~a lot of extra work for you both~ this change. 

Thanks Vigoren for all the work on SC 2.0 and a pre-thanks to you too Unsoluble for what I'm sure will eventually be a great revision to ST as well.

**Comment by unsoluble** [comment]
Sorry for letting this languish without further comment, but it's clearly not going to happen. :)
