### ISSUE TITLE
Investigate support for multiple moons

### ISSUE THREAD

**Issue by Doomixdo** [unsoluble/smalltime#81]
It would be amazing if players could see different moons, of different colors

**Comment by unsoluble** [comment]
Sorry could you elaborate on this? Different... moons? Per player?

**Comment by Doomixdo** [comment]
Sorry for not explaining myself better. I mean something purely cosmetic. For now players see the position of the sun and the moon as seen on earth, but it would be nice if different moons could be seen at night. For example, in a game that has a world with three moons of different colors and sizes. Something like on simple calendar module.

**Comment by unsoluble** [comment]
Ah, okay. Yeah, supporting more than one moon is more than my current design can handle. I'll leave this up as a possible investigation down the road, but it's not _terribly_ likely to happen. :)

**Comment by unsoluble** [comment]
(Yeah, after thinking about this for... over a year (oof), it's not gonna be something I'll implement, sorry.)
