### ISSUE TITLE
Allow for fine-grained view/control of time

### ISSUE THREAD

**Issue by NateHawk85** [unsoluble/smalltime#83]
I absolutely love the style and simplicity of this module. The only two things holding me back from completely switching off Calendar/Weather and moving to this are 1) a stop/start button (which yes, is available via SimpleCalendar, but it's so nice being able to switch without opening that window) and 2) the ability to see time in second increments. 

![image](https://user-images.githubusercontent.com/7596412/132619640-87e787b0-0d11-4ed2-82db-2ed9aab1b0dc.png)

Love your work, by the way. Thank you for all you do in this community! :)

**Comment by unsoluble** [comment]
Appreciate the kind words! Glad you find my stuff useful. :)

For stop/start, Shift-click the time (requires Simple Calendar).

As for seconds, I don't _think_ that's going to happen, as there just isn't room in the div for that. But I'll think about it.

**Comment by XtraButtery** [comment]
Recently started using the module in favour Calendar/Weather and would like to +1 the request for seconds, with a small suggestion. When using the 24 hour clock there is extra space present in the UI.

![image](https://user-images.githubusercontent.com/35461692/132648903-87b07e16-8fb4-4b58-b7f2-e6f516f85105.png)

Perhaps enabling seconds only when using the 24-Hour clock could be an option as this would allow for the extra information without compromising on the "small" aspect of SmallTime

**Comment by unsoluble** [comment]
Not a bad compromise solution; will play around with this. :)

**Comment by unsoluble** [comment]
Implemented in 1.13.0 (checkbox in settings, when 24hr mode is selected).
