### ISSUE TITLE
Feature Request: Option to Integrate SimpleCalendar's seasonal Sunrise/Sunset changes

### ISSUE THREAD

**Issue by XtraButtery** [unsoluble/smalltime#84]
Simple Calendar has recently expanded its list of features with it's 1.3.39 release ([https://github.com/vigoren/foundryvtt-simple-calendar/releases/tag/v1.3.39](https://github.com/vigoren/foundryvtt-simple-calendar/releases/tag/v1.3.39)) including the ability to determine the time of sunrise and sunset based on the seasons and the current date for more realistic sunrise/sunset times throughout the in-game year.

As there is already some crossover between SmallTime and Simple Calendar it would be nice if SmallTime could simply take the more accurate sunrise/sunset times from Simple Calendar when both modules are present.

**Comment by unsoluble** [comment]
Already in the works :)

**Comment by unsoluble** [comment]
Implemented in 1.12.0 😄
