### ISSUE TITLE
Feature Request: lock/unlock button or option for the graphical slider

### ISSUE THREAD

**Issue by MrPotatoZed** [unsoluble/smalltime#85]
On the one hand being able to change the time with a simple click and drag is awesome and the graphical interface is super intuitive. On the other hand it's pretty easy to click and drag the sun/moon by accident. With the buttons a misclick is easily fixed but the slider can quickly make big changes. If you don't remember what time it was before the misclick you're kind of out of luck. Getting it pretty close isn't the end of the world but it would be cool to have something to help protect against misclicks. A slider "lock/unlock" button or option would be appreciated.

**Comment by unsoluble** [comment]
Hmm. Can't say I've ever heard of anyone having trouble with accidental clicks there before, so at this point I don't think it's likely a common enough issue to warrant extra UI to manage. But I'll think about it a bit. :)

**Comment by MrPotatoZed** [comment]
No worries; just lodging my vote. Thanks for considering it and great mod either way.

**Comment by Runesmite** [comment]
I agree a slider would be awesome. I gone to quickly move the smalltime box and out of habit click the top bar to do so, quickly changing the time of day. It'd be great if it could be toggled to a locked state, and then that bar could be used to then drag the box around for the GM. Not game-breaking by any means, but I wanted to cast my vote as well. Thank you for the work you've put in on this great mod!

**Comment by unsoluble** [comment]
Quick fix for this, but should be a decent compromise: In 1.13.3, clicks in the slider track don't make changes, only grabbing the sun/moon directly.
