### ISSUE TITLE
Issue with visibility

### ISSUE THREAD

**Issue by remiverdel** [unsoluble/smalltime#87]
Hi,

Thanks for the great module.
Just saw a problem on the visibility side of things. I checked visible for player to 'none' but when I try to connect as a player, I still see the smalltime window and can move it around. I sure can't interact with it, but the functionality doesn't seem to correctly hide it for the players.

Cheers,

**Comment by unsoluble** [comment]
Hmm! Just to be sure, did you only change the _default_ for this setting in the Module Settings screen perhaps, and not the actual scene-specific setting in the config for the scene itself?

**Comment by remiverdel** [comment]
Hi John,

I just changed the default option

**Comment by unsoluble** [comment]
Yeah so that default setting will apply to any _new scenes_ you create from this point forward, but any existing scenes that you'd like to behave this way you'll need to go into their scene settings and explicitly choose this view permission.

**Comment by remiverdel** [comment]
Oh thanks! I didn’t know these settings were there. My bad!
Thanks again for such a module

Cheers,

**Comment by unsoluble** [comment]
No prob! Glad you're liking it. :)
