### ISSUE TITLE
Smalltime window causing weird interaction with console.

### ISSUE THREAD

**Issue by Brimcon** [unsoluble/smalltime#89]
If you have the right sidebar minimized and have the Small Time window relatively close to the right side of the Foundry Window, opening the console and closing it quickly creates a gray space that only goes away if you move the map to the right side of the scene.
![image](https://user-images.githubusercontent.com/7198283/134777989-e629ed97-7f47-49a3-bd45-7d374777a0c8.png)
0.8.9 Foundry, 1.13 Small Time

**Comment by unsoluble** [comment]
Uhhhh weird? I cannot reproduce that, no matter what I try. What are you using to view Foundry here?

**Comment by Brimcon** [comment]
The Electrum App. I haven't tried with Chrome browser yet.

**Comment by unsoluble** [comment]
Yeah I can't repro this in (macOS) Electron, Chrome, or Firefox.

**Comment by Brimcon** [comment]
This is how close I have it when opening/closing the Console
![image](https://user-images.githubusercontent.com/7198283/134783932-4069e089-cd59-4cb6-be12-416a456cf1e5.png)

This is using Windows version of the Foundry/Electrum App.

**Comment by unsoluble** [comment]
Yeah, weird. Seems to be limited to Windows/Electron, which is a scenario I can't test on here. And since it's just a temporary visual glitch and also rarely triggered, not going to bother digging further. But I do appreciate the report nonetheless, thanks. :)
