### ISSUE TITLE
Feature Request: Quarter Days

### ISSUE THREAD

**Issue by SCHayworth** [unsoluble/smalltime#90]
For games using the Year 0 Engine (and for people like me who like to hack in Y0E journey rules into other games), I'd love to be able to configure the forward and back buttons, and perhaps the time as well, to use quarter days rather than standard clock time.

It looks like the easiest way of achieving the same effect would be to increase the number of minutes on the "Large Step Amount" setting to be 6 hours, but it would be nice to see the time field read something like "First Quarter" rather than standard clock time. Also, I say "easiest way" without being a coder, so I understand if this is one of those things that isn't as simple to program as it seems.

**Comment by unsoluble** [comment]
Huh. Curious. What Foundry game system(s) would this be relevant in? I could look at adding it conditionally.

**Comment by SCHayworth** [comment]
Forbidden Lands is my specific use case, but I’m pretty sure that at least
some of the other Year 0 Engine games use it as well. I also tend to hack
in some of the Y0E journey rules into D&D, but that’s just me.
