### ISSUE TITLE
[Feature request] In-Game alarms

### ISSUE THREAD

**Issue by Voidchimera** [unsoluble/smalltime#95]
I've been loving your module quite a lot, but one feature that would be amazing for most games would be the possibility to schedule alarms that would trigger with the advancement of the clock in-game.

Admittedly I'm not sure if this is the adequate module to ask for such a feature, but it'd add so much to SmallTime since it already deals with time management. The uses for these alert I can think for this could be to keep track of torches, lamps, hunger, spells, time limits and such, and if you can 'pause' these alarms and keep them in a drop-down menu would allow keeping track of how many hours of light they have left if they decide to put out a torch and save it for later.

**Comment by unsoluble** [comment]
Yeah while that's certainly a fair idea for a module to tackle, I'm pretty sure it's not going to be _this_ module. :)
