### ISSUE TITLE
User Lacks Permission to Change Setting {ID}

### ISSUE THREAD

**Issue by Shuggaloaf** [unsoluble/smalltime#98]
Hi Unsoluble. Getting the above error on player screens only whenever the time crosses midnight (either direction).

The ID was an actual ID number and I looked in Settings.db and found that it had this line there: `{"_id":"tB10GxBKyUHJ1ST9","key":"smalltime.moon-phase","value":"0"}` 

Any idea what may be happening here?

edit:
all appears to work fine btw, with the moon phase slider still moving for players. 
Details I forgot to give: FVTT 0.8.9, ST 1.13.2, DnD5e 1.5.3

**Comment by unsoluble** [comment]
Updating SmallTime would be the first thing to try. :)

**Comment by Shuggaloaf** [comment]
Hey look man I don't need you responding incredibly quickly and then making sense OK? ;-)

Kidding aside, that was it. Noob'd out on that one, my bad. I thought I has updated within the last few weeks and I saw last release 28 days ago and made the sin of assumption. haha 

Closing it out.
